// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: video.proto

// protoc -I=. -I=$GOPATH/pkg/mod --go-grpc_out=. --gogo_out=. *.proto

package videoApi

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,json=user_name,proto3" json:"user_name"`
	FollowCount          int64    `protobuf:"varint,3,opt,name=FollowCount,json=follow_count,proto3" json:"follow_count"`
	FollowerCount        int64    `protobuf:"varint,4,opt,name=FollowerCount,json=follower_count,proto3" json:"follower_count"`
	IsFollow             int64    `protobuf:"varint,5,opt,name=IsFollow,json=is_follow,proto3" json:"is_follow"`
	Avatar               string   `protobuf:"bytes,6,opt,name=Avatar,json=avatar,proto3" json:"avatar"`
	PublishNum           int64    `protobuf:"varint,7,opt,name=PublishNum,json=publish_num,proto3" json:"publish_num"`
	FavouriteNum         int64    `protobuf:"varint,8,opt,name=FavouriteNum,json=favourite_num,proto3" json:"favourite_num"`
	LikeNum              int64    `protobuf:"varint,9,opt,name=LikeNum,json=like_num,proto3" json:"like_num"`
	ReceivedLikeNum      int64    `protobuf:"varint,10,opt,name=ReceivedLikeNum,json=received_like_num,proto3" json:"received_like_num"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{0}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetFollowCount() int64 {
	if m != nil {
		return m.FollowCount
	}
	return 0
}

func (m *UserInfo) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *UserInfo) GetIsFollow() int64 {
	if m != nil {
		return m.IsFollow
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetPublishNum() int64 {
	if m != nil {
		return m.PublishNum
	}
	return 0
}

func (m *UserInfo) GetFavouriteNum() int64 {
	if m != nil {
		return m.FavouriteNum
	}
	return 0
}

func (m *UserInfo) GetLikeNum() int64 {
	if m != nil {
		return m.LikeNum
	}
	return 0
}

func (m *UserInfo) GetReceivedLikeNum() int64 {
	if m != nil {
		return m.ReceivedLikeNum
	}
	return 0
}

type VideoInfo struct {
	VideoID              string    `protobuf:"bytes,1,opt,name=VideoID,json=video_id,proto3" json:"video_id"`
	Author               *UserInfo `protobuf:"bytes,2,opt,name=Author,json=author,proto3" json:"author"`
	PlayUrl              string    `protobuf:"bytes,3,opt,name=PlayUrl,json=play_url,proto3" json:"play_url"`
	CoverUrl             string    `protobuf:"bytes,4,opt,name=CoverUrl,json=cover_url,proto3" json:"cover_url"`
	FavoriteCount        int64     `protobuf:"varint,5,opt,name=FavoriteCount,json=favorite_count,proto3" json:"favorite_count"`
	CommentCount         int64     `protobuf:"varint,6,opt,name=CommentCount,json=comment_count,proto3" json:"comment_count"`
	IsFavorite           int64     `protobuf:"varint,7,opt,name=IsFavorite,json=is_favorite,proto3" json:"is_favorite"`
	Title                string    `protobuf:"bytes,8,opt,name=Title,json=title,proto3" json:"title"`
	IsEncoding           bool      `protobuf:"varint,9,opt,name=IsEncoding,json=is_encoding,proto3" json:"is_encoding"`
	CollectCount         int64     `protobuf:"varint,10,opt,name=CollectCount,json=collect_count,proto3" json:"collect_count"`
	HasLike              int64     `protobuf:"varint,11,opt,name=HasLike,json=has_like,proto3" json:"has_like"`
	HasCollect           int64     `protobuf:"varint,12,opt,name=HasCollect,json=has_collect,proto3" json:"has_collect"`
	Description          string    `protobuf:"bytes,13,opt,name=Description,json=description,proto3" json:"description"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VideoInfo) Reset()         { *m = VideoInfo{} }
func (m *VideoInfo) String() string { return proto.CompactTextString(m) }
func (*VideoInfo) ProtoMessage()    {}
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{1}
}
func (m *VideoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoInfo.Unmarshal(m, b)
}
func (m *VideoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoInfo.Marshal(b, m, deterministic)
}
func (m *VideoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoInfo.Merge(m, src)
}
func (m *VideoInfo) XXX_Size() int {
	return xxx_messageInfo_VideoInfo.Size(m)
}
func (m *VideoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VideoInfo proto.InternalMessageInfo

func (m *VideoInfo) GetVideoID() string {
	if m != nil {
		return m.VideoID
	}
	return ""
}

func (m *VideoInfo) GetAuthor() *UserInfo {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *VideoInfo) GetPlayUrl() string {
	if m != nil {
		return m.PlayUrl
	}
	return ""
}

func (m *VideoInfo) GetCoverUrl() string {
	if m != nil {
		return m.CoverUrl
	}
	return ""
}

func (m *VideoInfo) GetFavoriteCount() int64 {
	if m != nil {
		return m.FavoriteCount
	}
	return 0
}

func (m *VideoInfo) GetCommentCount() int64 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *VideoInfo) GetIsFavorite() int64 {
	if m != nil {
		return m.IsFavorite
	}
	return 0
}

func (m *VideoInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoInfo) GetIsEncoding() bool {
	if m != nil {
		return m.IsEncoding
	}
	return false
}

func (m *VideoInfo) GetCollectCount() int64 {
	if m != nil {
		return m.CollectCount
	}
	return 0
}

func (m *VideoInfo) GetHasLike() int64 {
	if m != nil {
		return m.HasLike
	}
	return 0
}

func (m *VideoInfo) GetHasCollect() int64 {
	if m != nil {
		return m.HasCollect
	}
	return 0
}

func (m *VideoInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type VideoFeedReq struct {
	LatestTime           int64    `protobuf:"varint,1,opt,name=LatestTime,json=latest_time,proto3" json:"latest_time"`
	UserId               string   `protobuf:"bytes,2,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoFeedReq) Reset()         { *m = VideoFeedReq{} }
func (m *VideoFeedReq) String() string { return proto.CompactTextString(m) }
func (*VideoFeedReq) ProtoMessage()    {}
func (*VideoFeedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{2}
}
func (m *VideoFeedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFeedReq.Unmarshal(m, b)
}
func (m *VideoFeedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFeedReq.Marshal(b, m, deterministic)
}
func (m *VideoFeedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFeedReq.Merge(m, src)
}
func (m *VideoFeedReq) XXX_Size() int {
	return xxx_messageInfo_VideoFeedReq.Size(m)
}
func (m *VideoFeedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFeedReq.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFeedReq proto.InternalMessageInfo

func (m *VideoFeedReq) GetLatestTime() int64 {
	if m != nil {
		return m.LatestTime
	}
	return 0
}

func (m *VideoFeedReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type VideoFeedResp struct {
	VideoList            []*VideoInfo `protobuf:"bytes,1,rep,name=VideoList,json=video_info,proto3" json:"video_info"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VideoFeedResp) Reset()         { *m = VideoFeedResp{} }
func (m *VideoFeedResp) String() string { return proto.CompactTextString(m) }
func (*VideoFeedResp) ProtoMessage()    {}
func (*VideoFeedResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{3}
}
func (m *VideoFeedResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFeedResp.Unmarshal(m, b)
}
func (m *VideoFeedResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFeedResp.Marshal(b, m, deterministic)
}
func (m *VideoFeedResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFeedResp.Merge(m, src)
}
func (m *VideoFeedResp) XXX_Size() int {
	return xxx_messageInfo_VideoFeedResp.Size(m)
}
func (m *VideoFeedResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFeedResp.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFeedResp proto.InternalMessageInfo

func (m *VideoFeedResp) GetVideoList() []*VideoInfo {
	if m != nil {
		return m.VideoList
	}
	return nil
}

type UploadVideoReq struct {
	Description          string   `protobuf:"bytes,1,opt,name=Description,json=description,proto3" json:"description"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,json=title,proto3" json:"title"`
	VideoTag             []string `protobuf:"bytes,3,rep,name=VideoTag,json=video_tag,proto3" json:"video_tag"`
	FileExtension        string   `protobuf:"bytes,4,opt,name=FileExtension,json=file_extension,proto3" json:"file_extension"`
	UserId               string   `protobuf:"bytes,5,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	VideoId              string   `protobuf:"bytes,6,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadVideoReq) Reset()         { *m = UploadVideoReq{} }
func (m *UploadVideoReq) String() string { return proto.CompactTextString(m) }
func (*UploadVideoReq) ProtoMessage()    {}
func (*UploadVideoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{4}
}
func (m *UploadVideoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadVideoReq.Unmarshal(m, b)
}
func (m *UploadVideoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadVideoReq.Marshal(b, m, deterministic)
}
func (m *UploadVideoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadVideoReq.Merge(m, src)
}
func (m *UploadVideoReq) XXX_Size() int {
	return xxx_messageInfo_UploadVideoReq.Size(m)
}
func (m *UploadVideoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadVideoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadVideoReq proto.InternalMessageInfo

func (m *UploadVideoReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UploadVideoReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UploadVideoReq) GetVideoTag() []string {
	if m != nil {
		return m.VideoTag
	}
	return nil
}

func (m *UploadVideoReq) GetFileExtension() string {
	if m != nil {
		return m.FileExtension
	}
	return ""
}

func (m *UploadVideoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UploadVideoReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type UploadVideoResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,json=token,proto3" json:"token"`
	ResourceKey          string   `protobuf:"bytes,2,opt,name=ResourceKey,json=resource_key,proto3" json:"resource_key"`
	VideoId              string   `protobuf:"bytes,3,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadVideoResp) Reset()         { *m = UploadVideoResp{} }
func (m *UploadVideoResp) String() string { return proto.CompactTextString(m) }
func (*UploadVideoResp) ProtoMessage()    {}
func (*UploadVideoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5}
}
func (m *UploadVideoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadVideoResp.Unmarshal(m, b)
}
func (m *UploadVideoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadVideoResp.Marshal(b, m, deterministic)
}
func (m *UploadVideoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadVideoResp.Merge(m, src)
}
func (m *UploadVideoResp) XXX_Size() int {
	return xxx_messageInfo_UploadVideoResp.Size(m)
}
func (m *UploadVideoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadVideoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadVideoResp proto.InternalMessageInfo

func (m *UploadVideoResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UploadVideoResp) GetResourceKey() string {
	if m != nil {
		return m.ResourceKey
	}
	return ""
}

func (m *UploadVideoResp) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type DownloadReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadReq) Reset()         { *m = DownloadReq{} }
func (m *DownloadReq) String() string { return proto.CompactTextString(m) }
func (*DownloadReq) ProtoMessage()    {}
func (*DownloadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{6}
}
func (m *DownloadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadReq.Unmarshal(m, b)
}
func (m *DownloadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadReq.Marshal(b, m, deterministic)
}
func (m *DownloadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadReq.Merge(m, src)
}
func (m *DownloadReq) XXX_Size() int {
	return xxx_messageInfo_DownloadReq.Size(m)
}
func (m *DownloadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadReq.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadReq proto.InternalMessageInfo

type DownLoadResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,json=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownLoadResp) Reset()         { *m = DownLoadResp{} }
func (m *DownLoadResp) String() string { return proto.CompactTextString(m) }
func (*DownLoadResp) ProtoMessage()    {}
func (*DownLoadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{7}
}
func (m *DownLoadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownLoadResp.Unmarshal(m, b)
}
func (m *DownLoadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownLoadResp.Marshal(b, m, deterministic)
}
func (m *DownLoadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownLoadResp.Merge(m, src)
}
func (m *DownLoadResp) XXX_Size() int {
	return xxx_messageInfo_DownLoadResp.Size(m)
}
func (m *DownLoadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DownLoadResp.DiscardUnknown(m)
}

var xxx_messageInfo_DownLoadResp proto.InternalMessageInfo

func (m *DownLoadResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetVideoInfoByIdReq struct {
	VideoId              string   `protobuf:"bytes,1,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoInfoByIdReq) Reset()         { *m = GetVideoInfoByIdReq{} }
func (m *GetVideoInfoByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetVideoInfoByIdReq) ProtoMessage()    {}
func (*GetVideoInfoByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{8}
}
func (m *GetVideoInfoByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoInfoByIdReq.Unmarshal(m, b)
}
func (m *GetVideoInfoByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoInfoByIdReq.Marshal(b, m, deterministic)
}
func (m *GetVideoInfoByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoInfoByIdReq.Merge(m, src)
}
func (m *GetVideoInfoByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetVideoInfoByIdReq.Size(m)
}
func (m *GetVideoInfoByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoInfoByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoInfoByIdReq proto.InternalMessageInfo

func (m *GetVideoInfoByIdReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type GetVideoInfoByIdResp struct {
	Video                *VideoInfo `protobuf:"bytes,1,opt,name=Video,json=video,proto3" json:"video"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetVideoInfoByIdResp) Reset()         { *m = GetVideoInfoByIdResp{} }
func (m *GetVideoInfoByIdResp) String() string { return proto.CompactTextString(m) }
func (*GetVideoInfoByIdResp) ProtoMessage()    {}
func (*GetVideoInfoByIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{9}
}
func (m *GetVideoInfoByIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoInfoByIdResp.Unmarshal(m, b)
}
func (m *GetVideoInfoByIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoInfoByIdResp.Marshal(b, m, deterministic)
}
func (m *GetVideoInfoByIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoInfoByIdResp.Merge(m, src)
}
func (m *GetVideoInfoByIdResp) XXX_Size() int {
	return xxx_messageInfo_GetVideoInfoByIdResp.Size(m)
}
func (m *GetVideoInfoByIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoInfoByIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoInfoByIdResp proto.InternalMessageInfo

func (m *GetVideoInfoByIdResp) GetVideo() *VideoInfo {
	if m != nil {
		return m.Video
	}
	return nil
}

type RebackOneReq struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,json=title,proto3" json:"title"`
	CoverUrl             string   `protobuf:"bytes,2,opt,name=CoverUrl,json=cover_url,proto3" json:"cover_url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebackOneReq) Reset()         { *m = RebackOneReq{} }
func (m *RebackOneReq) String() string { return proto.CompactTextString(m) }
func (*RebackOneReq) ProtoMessage()    {}
func (*RebackOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{10}
}
func (m *RebackOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebackOneReq.Unmarshal(m, b)
}
func (m *RebackOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebackOneReq.Marshal(b, m, deterministic)
}
func (m *RebackOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebackOneReq.Merge(m, src)
}
func (m *RebackOneReq) XXX_Size() int {
	return xxx_messageInfo_RebackOneReq.Size(m)
}
func (m *RebackOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RebackOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_RebackOneReq proto.InternalMessageInfo

func (m *RebackOneReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RebackOneReq) GetCoverUrl() string {
	if m != nil {
		return m.CoverUrl
	}
	return ""
}

type RebackOneResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebackOneResp) Reset()         { *m = RebackOneResp{} }
func (m *RebackOneResp) String() string { return proto.CompactTextString(m) }
func (*RebackOneResp) ProtoMessage()    {}
func (*RebackOneResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{11}
}
func (m *RebackOneResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebackOneResp.Unmarshal(m, b)
}
func (m *RebackOneResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebackOneResp.Marshal(b, m, deterministic)
}
func (m *RebackOneResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebackOneResp.Merge(m, src)
}
func (m *RebackOneResp) XXX_Size() int {
	return xxx_messageInfo_RebackOneResp.Size(m)
}
func (m *RebackOneResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RebackOneResp.DiscardUnknown(m)
}

var xxx_messageInfo_RebackOneResp proto.InternalMessageInfo

type RebackTwoReq struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	ResourceKey          []string `protobuf:"bytes,2,rep,name=ResourceKey,proto3" json:"ResourceKey,omitempty"`
	Type                 []string `protobuf:"bytes,3,rep,name=Type,proto3" json:"Type,omitempty"`
	VideoId              string   `protobuf:"bytes,4,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	Quality              []int64  `protobuf:"varint,5,rep,packed,name=Quality,proto3" json:"Quality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebackTwoReq) Reset()         { *m = RebackTwoReq{} }
func (m *RebackTwoReq) String() string { return proto.CompactTextString(m) }
func (*RebackTwoReq) ProtoMessage()    {}
func (*RebackTwoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{12}
}
func (m *RebackTwoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebackTwoReq.Unmarshal(m, b)
}
func (m *RebackTwoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebackTwoReq.Marshal(b, m, deterministic)
}
func (m *RebackTwoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebackTwoReq.Merge(m, src)
}
func (m *RebackTwoReq) XXX_Size() int {
	return xxx_messageInfo_RebackTwoReq.Size(m)
}
func (m *RebackTwoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RebackTwoReq.DiscardUnknown(m)
}

var xxx_messageInfo_RebackTwoReq proto.InternalMessageInfo

func (m *RebackTwoReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RebackTwoReq) GetResourceKey() []string {
	if m != nil {
		return m.ResourceKey
	}
	return nil
}

func (m *RebackTwoReq) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *RebackTwoReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *RebackTwoReq) GetQuality() []int64 {
	if m != nil {
		return m.Quality
	}
	return nil
}

type RebackTwoResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebackTwoResp) Reset()         { *m = RebackTwoResp{} }
func (m *RebackTwoResp) String() string { return proto.CompactTextString(m) }
func (*RebackTwoResp) ProtoMessage()    {}
func (*RebackTwoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{13}
}
func (m *RebackTwoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebackTwoResp.Unmarshal(m, b)
}
func (m *RebackTwoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebackTwoResp.Marshal(b, m, deterministic)
}
func (m *RebackTwoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebackTwoResp.Merge(m, src)
}
func (m *RebackTwoResp) XXX_Size() int {
	return xxx_messageInfo_RebackTwoResp.Size(m)
}
func (m *RebackTwoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RebackTwoResp.DiscardUnknown(m)
}

var xxx_messageInfo_RebackTwoResp proto.InternalMessageInfo

type PublishListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishListReq) Reset()         { *m = PublishListReq{} }
func (m *PublishListReq) String() string { return proto.CompactTextString(m) }
func (*PublishListReq) ProtoMessage()    {}
func (*PublishListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{14}
}
func (m *PublishListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishListReq.Unmarshal(m, b)
}
func (m *PublishListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishListReq.Marshal(b, m, deterministic)
}
func (m *PublishListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishListReq.Merge(m, src)
}
func (m *PublishListReq) XXX_Size() int {
	return xxx_messageInfo_PublishListReq.Size(m)
}
func (m *PublishListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishListReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishListReq proto.InternalMessageInfo

func (m *PublishListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type PublishListResp struct {
	Video                []*VideoInfo `protobuf:"bytes,1,rep,name=Video,json=video,proto3" json:"video"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PublishListResp) Reset()         { *m = PublishListResp{} }
func (m *PublishListResp) String() string { return proto.CompactTextString(m) }
func (*PublishListResp) ProtoMessage()    {}
func (*PublishListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{15}
}
func (m *PublishListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishListResp.Unmarshal(m, b)
}
func (m *PublishListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishListResp.Marshal(b, m, deterministic)
}
func (m *PublishListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishListResp.Merge(m, src)
}
func (m *PublishListResp) XXX_Size() int {
	return xxx_messageInfo_PublishListResp.Size(m)
}
func (m *PublishListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishListResp.DiscardUnknown(m)
}

var xxx_messageInfo_PublishListResp proto.InternalMessageInfo

func (m *PublishListResp) GetVideo() []*VideoInfo {
	if m != nil {
		return m.Video
	}
	return nil
}

type SearchVideoByVideoTagReq struct {
	VideoTag             string   `protobuf:"bytes,1,opt,name=VideoTag,json=video_tag,proto3" json:"video_tag"`
	UserId               string   `protobuf:"bytes,2,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchVideoByVideoTagReq) Reset()         { *m = SearchVideoByVideoTagReq{} }
func (m *SearchVideoByVideoTagReq) String() string { return proto.CompactTextString(m) }
func (*SearchVideoByVideoTagReq) ProtoMessage()    {}
func (*SearchVideoByVideoTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{16}
}
func (m *SearchVideoByVideoTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchVideoByVideoTagReq.Unmarshal(m, b)
}
func (m *SearchVideoByVideoTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchVideoByVideoTagReq.Marshal(b, m, deterministic)
}
func (m *SearchVideoByVideoTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchVideoByVideoTagReq.Merge(m, src)
}
func (m *SearchVideoByVideoTagReq) XXX_Size() int {
	return xxx_messageInfo_SearchVideoByVideoTagReq.Size(m)
}
func (m *SearchVideoByVideoTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchVideoByVideoTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchVideoByVideoTagReq proto.InternalMessageInfo

func (m *SearchVideoByVideoTagReq) GetVideoTag() string {
	if m != nil {
		return m.VideoTag
	}
	return ""
}

func (m *SearchVideoByVideoTagReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SearchVideoByVideoTagResp struct {
	Video                []*VideoInfo `protobuf:"bytes,1,rep,name=Video,json=video_info,proto3" json:"video_info"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SearchVideoByVideoTagResp) Reset()         { *m = SearchVideoByVideoTagResp{} }
func (m *SearchVideoByVideoTagResp) String() string { return proto.CompactTextString(m) }
func (*SearchVideoByVideoTagResp) ProtoMessage()    {}
func (*SearchVideoByVideoTagResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{17}
}
func (m *SearchVideoByVideoTagResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchVideoByVideoTagResp.Unmarshal(m, b)
}
func (m *SearchVideoByVideoTagResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchVideoByVideoTagResp.Marshal(b, m, deterministic)
}
func (m *SearchVideoByVideoTagResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchVideoByVideoTagResp.Merge(m, src)
}
func (m *SearchVideoByVideoTagResp) XXX_Size() int {
	return xxx_messageInfo_SearchVideoByVideoTagResp.Size(m)
}
func (m *SearchVideoByVideoTagResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchVideoByVideoTagResp.DiscardUnknown(m)
}

var xxx_messageInfo_SearchVideoByVideoTagResp proto.InternalMessageInfo

func (m *SearchVideoByVideoTagResp) GetVideo() []*VideoInfo {
	if m != nil {
		return m.Video
	}
	return nil
}

type InrcCommentCountReq struct {
	VideoId              string   `protobuf:"bytes,1,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InrcCommentCountReq) Reset()         { *m = InrcCommentCountReq{} }
func (m *InrcCommentCountReq) String() string { return proto.CompactTextString(m) }
func (*InrcCommentCountReq) ProtoMessage()    {}
func (*InrcCommentCountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{18}
}
func (m *InrcCommentCountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InrcCommentCountReq.Unmarshal(m, b)
}
func (m *InrcCommentCountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InrcCommentCountReq.Marshal(b, m, deterministic)
}
func (m *InrcCommentCountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InrcCommentCountReq.Merge(m, src)
}
func (m *InrcCommentCountReq) XXX_Size() int {
	return xxx_messageInfo_InrcCommentCountReq.Size(m)
}
func (m *InrcCommentCountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InrcCommentCountReq.DiscardUnknown(m)
}

var xxx_messageInfo_InrcCommentCountReq proto.InternalMessageInfo

func (m *InrcCommentCountReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *InrcCommentCountReq) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type InrcCommentCountResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InrcCommentCountResp) Reset()         { *m = InrcCommentCountResp{} }
func (m *InrcCommentCountResp) String() string { return proto.CompactTextString(m) }
func (*InrcCommentCountResp) ProtoMessage()    {}
func (*InrcCommentCountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{19}
}
func (m *InrcCommentCountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InrcCommentCountResp.Unmarshal(m, b)
}
func (m *InrcCommentCountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InrcCommentCountResp.Marshal(b, m, deterministic)
}
func (m *InrcCommentCountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InrcCommentCountResp.Merge(m, src)
}
func (m *InrcCommentCountResp) XXX_Size() int {
	return xxx_messageInfo_InrcCommentCountResp.Size(m)
}
func (m *InrcCommentCountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InrcCommentCountResp.DiscardUnknown(m)
}

var xxx_messageInfo_InrcCommentCountResp proto.InternalMessageInfo

type UpdateVideoReq struct {
	Video                *VideoInfo `protobuf:"bytes,1,opt,name=Video,proto3" json:"Video,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateVideoReq) Reset()         { *m = UpdateVideoReq{} }
func (m *UpdateVideoReq) String() string { return proto.CompactTextString(m) }
func (*UpdateVideoReq) ProtoMessage()    {}
func (*UpdateVideoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{20}
}
func (m *UpdateVideoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVideoReq.Unmarshal(m, b)
}
func (m *UpdateVideoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVideoReq.Marshal(b, m, deterministic)
}
func (m *UpdateVideoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVideoReq.Merge(m, src)
}
func (m *UpdateVideoReq) XXX_Size() int {
	return xxx_messageInfo_UpdateVideoReq.Size(m)
}
func (m *UpdateVideoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVideoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVideoReq proto.InternalMessageInfo

func (m *UpdateVideoReq) GetVideo() *VideoInfo {
	if m != nil {
		return m.Video
	}
	return nil
}

type UpdateVideoResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateVideoResp) Reset()         { *m = UpdateVideoResp{} }
func (m *UpdateVideoResp) String() string { return proto.CompactTextString(m) }
func (*UpdateVideoResp) ProtoMessage()    {}
func (*UpdateVideoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{21}
}
func (m *UpdateVideoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateVideoResp.Unmarshal(m, b)
}
func (m *UpdateVideoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateVideoResp.Marshal(b, m, deterministic)
}
func (m *UpdateVideoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateVideoResp.Merge(m, src)
}
func (m *UpdateVideoResp) XXX_Size() int {
	return xxx_messageInfo_UpdateVideoResp.Size(m)
}
func (m *UpdateVideoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateVideoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateVideoResp proto.InternalMessageInfo

type IncrFiledReq struct {
	Filed                string   `protobuf:"bytes,1,opt,name=Filed,json=filed,proto3" json:"filed"`
	Value                int64    `protobuf:"varint,2,opt,name=Value,json=value,proto3" json:"value"`
	VideoId              string   `protobuf:"bytes,3,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrFiledReq) Reset()         { *m = IncrFiledReq{} }
func (m *IncrFiledReq) String() string { return proto.CompactTextString(m) }
func (*IncrFiledReq) ProtoMessage()    {}
func (*IncrFiledReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{22}
}
func (m *IncrFiledReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrFiledReq.Unmarshal(m, b)
}
func (m *IncrFiledReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrFiledReq.Marshal(b, m, deterministic)
}
func (m *IncrFiledReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrFiledReq.Merge(m, src)
}
func (m *IncrFiledReq) XXX_Size() int {
	return xxx_messageInfo_IncrFiledReq.Size(m)
}
func (m *IncrFiledReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrFiledReq.DiscardUnknown(m)
}

var xxx_messageInfo_IncrFiledReq proto.InternalMessageInfo

func (m *IncrFiledReq) GetFiled() string {
	if m != nil {
		return m.Filed
	}
	return ""
}

func (m *IncrFiledReq) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *IncrFiledReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type IncrFiledResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrFiledResp) Reset()         { *m = IncrFiledResp{} }
func (m *IncrFiledResp) String() string { return proto.CompactTextString(m) }
func (*IncrFiledResp) ProtoMessage()    {}
func (*IncrFiledResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{23}
}
func (m *IncrFiledResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrFiledResp.Unmarshal(m, b)
}
func (m *IncrFiledResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrFiledResp.Marshal(b, m, deterministic)
}
func (m *IncrFiledResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrFiledResp.Merge(m, src)
}
func (m *IncrFiledResp) XXX_Size() int {
	return xxx_messageInfo_IncrFiledResp.Size(m)
}
func (m *IncrFiledResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrFiledResp.DiscardUnknown(m)
}

var xxx_messageInfo_IncrFiledResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UserInfo)(nil), "video.UserInfo")
	proto.RegisterType((*VideoInfo)(nil), "video.VideoInfo")
	proto.RegisterType((*VideoFeedReq)(nil), "video.VideoFeedReq")
	proto.RegisterType((*VideoFeedResp)(nil), "video.VideoFeedResp")
	proto.RegisterType((*UploadVideoReq)(nil), "video.UploadVideoReq")
	proto.RegisterType((*UploadVideoResp)(nil), "video.UploadVideoResp")
	proto.RegisterType((*DownloadReq)(nil), "video.DownloadReq")
	proto.RegisterType((*DownLoadResp)(nil), "video.DownLoadResp")
	proto.RegisterType((*GetVideoInfoByIdReq)(nil), "video.GetVideoInfoByIdReq")
	proto.RegisterType((*GetVideoInfoByIdResp)(nil), "video.GetVideoInfoByIdResp")
	proto.RegisterType((*RebackOneReq)(nil), "video.RebackOneReq")
	proto.RegisterType((*RebackOneResp)(nil), "video.RebackOneResp")
	proto.RegisterType((*RebackTwoReq)(nil), "video.RebackTwoReq")
	proto.RegisterType((*RebackTwoResp)(nil), "video.RebackTwoResp")
	proto.RegisterType((*PublishListReq)(nil), "video.PublishListReq")
	proto.RegisterType((*PublishListResp)(nil), "video.PublishListResp")
	proto.RegisterType((*SearchVideoByVideoTagReq)(nil), "video.SearchVideoByVideoTagReq")
	proto.RegisterType((*SearchVideoByVideoTagResp)(nil), "video.SearchVideoByVideoTagResp")
	proto.RegisterType((*InrcCommentCountReq)(nil), "video.InrcCommentCountReq")
	proto.RegisterType((*InrcCommentCountResp)(nil), "video.InrcCommentCountResp")
	proto.RegisterType((*UpdateVideoReq)(nil), "video.UpdateVideoReq")
	proto.RegisterType((*UpdateVideoResp)(nil), "video.UpdateVideoResp")
	proto.RegisterType((*IncrFiledReq)(nil), "video.IncrFiledReq")
	proto.RegisterType((*IncrFiledResp)(nil), "video.IncrFiledResp")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_0ad4ea8866efb1e3) }

var fileDescriptor_0ad4ea8866efb1e3 = []byte{
	// 1318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0xdf, 0x6e, 0xdb, 0xb6,
	0x17, 0x86, 0xa3, 0xd8, 0x89, 0x29, 0x3b, 0x6e, 0x99, 0xa4, 0xd0, 0xcf, 0xbf, 0x0b, 0x19, 0xc2,
	0xb0, 0x06, 0x05, 0x96, 0xac, 0x09, 0x10, 0x74, 0xe8, 0xb0, 0x21, 0xce, 0x9f, 0xd5, 0x68, 0xd0,
	0x65, 0xac, 0x53, 0x0c, 0xdd, 0x85, 0xa1, 0xc8, 0xb4, 0x23, 0x44, 0x96, 0x54, 0x51, 0x72, 0xe6,
	0x97, 0x18, 0x76, 0xbd, 0x67, 0x1b, 0xfc, 0x00, 0xbe, 0xdc, 0xf5, 0x2e, 0x06, 0x1e, 0x52, 0x12,
	0xe5, 0xd8, 0x4e, 0xae, 0xc4, 0x73, 0xc8, 0x8f, 0x3c, 0x3c, 0xe7, 0x3b, 0x1f, 0x6d, 0xa4, 0x8f,
	0xdd, 0x3e, 0x0d, 0xf6, 0xc3, 0x28, 0x88, 0x03, 0x5c, 0x06, 0xa3, 0xf9, 0xcd, 0xd0, 0x8d, 0x6f,
	0x93, 0x9b, 0x7d, 0x27, 0x18, 0x1d, 0x0c, 0x83, 0x61, 0x70, 0x00, 0xb3, 0x37, 0xc9, 0x00, 0x2c,
	0x30, 0x60, 0x24, 0x50, 0xd6, 0x3f, 0x1a, 0xda, 0xbc, 0x66, 0x34, 0xea, 0xf8, 0x83, 0x00, 0x7f,
	0x85, 0x2a, 0x30, 0xee, 0x1b, 0xa5, 0x56, 0x69, 0xaf, 0xda, 0xd6, 0x67, 0x53, 0x73, 0x23, 0x61,
	0x34, 0xea, 0xb9, 0x7d, 0x92, 0x0e, 0xf0, 0x2b, 0x81, 0xf8, 0x60, 0x8f, 0xa8, 0xb1, 0x06, 0xeb,
	0xea, 0xb3, 0xa9, 0x59, 0x85, 0x69, 0xdf, 0x1e, 0x51, 0x92, 0x0f, 0xf1, 0x11, 0xd2, 0x2f, 0x02,
	0xcf, 0x0b, 0xee, 0x4f, 0x83, 0xc4, 0x8f, 0x0d, 0xad, 0x55, 0xda, 0xd3, 0xda, 0xcf, 0x66, 0x53,
	0xb3, 0x36, 0x00, 0x77, 0xcf, 0xe1, 0x7e, 0x52, 0xb0, 0xf0, 0x77, 0xa8, 0x2e, 0x40, 0x34, 0x12,
	0xb0, 0x75, 0x80, 0xe1, 0xd9, 0xd4, 0xdc, 0x1a, 0xc8, 0x09, 0x09, 0x9c, 0xb3, 0x79, 0x6c, 0x1d,
	0x26, 0xc0, 0x46, 0x19, 0x50, 0x10, 0x9b, 0xcb, 0x7a, 0x62, 0x21, 0xc9, 0x87, 0xd8, 0x42, 0x95,
	0x93, 0xb1, 0x1d, 0xdb, 0x91, 0x51, 0x81, 0x5b, 0xa0, 0xd9, 0xd4, 0xac, 0xd8, 0xe0, 0x21, 0xf2,
	0x8b, 0xbf, 0x45, 0xe8, 0x2a, 0xb9, 0xf1, 0x5c, 0x76, 0xfb, 0x21, 0x19, 0x19, 0x1b, 0xb0, 0x63,
	0x63, 0x36, 0x35, 0xf5, 0x50, 0x78, 0x7b, 0x7e, 0x32, 0x22, 0xaa, 0x81, 0x8f, 0x51, 0xed, 0xc2,
	0x1e, 0x07, 0x49, 0xe4, 0xc6, 0x94, 0x63, 0x36, 0x01, 0xf3, 0x7c, 0x36, 0x35, 0xeb, 0x83, 0xd4,
	0x0f, 0xa8, 0xa2, 0x89, 0x5f, 0xa2, 0x8d, 0x4b, 0xf7, 0x0e, 0x20, 0x55, 0x80, 0xd4, 0x66, 0x53,
	0x73, 0xd3, 0x73, 0xef, 0xc4, 0xea, 0x6c, 0x84, 0x4f, 0x50, 0x83, 0x50, 0x87, 0xba, 0x63, 0xda,
	0x4f, 0x01, 0x08, 0x00, 0xbb, 0xb3, 0xa9, 0xf9, 0x3c, 0x92, 0x53, 0xbd, 0x0c, 0xf9, 0xd0, 0x65,
	0xfd, 0xbb, 0x8e, 0xaa, 0x9f, 0x38, 0x5b, 0xa0, 0xea, 0x2f, 0xd1, 0x86, 0x30, 0xce, 0x64, 0xd9,
	0xe1, 0x64, 0x60, 0x13, 0xaf, 0x7b, 0x36, 0xc2, 0x47, 0xa8, 0x72, 0x92, 0xc4, 0xb7, 0x41, 0x04,
	0x65, 0xd7, 0x0f, 0x1b, 0xfb, 0x82, 0x7f, 0x29, 0x7f, 0x64, 0x06, 0x61, 0x09, 0x91, 0x5f, 0xbe,
	0xfb, 0x95, 0x67, 0x4f, 0xae, 0x23, 0x0f, 0xaa, 0x2f, 0x77, 0x0f, 0x3d, 0x7b, 0xd2, 0x4b, 0x22,
	0x8f, 0x64, 0x23, 0x5e, 0xba, 0xd3, 0x60, 0x4c, 0x23, 0xbe, 0x72, 0x3d, 0xa7, 0x95, 0xc3, 0x7d,
	0xb0, 0x34, 0x1f, 0x02, 0x43, 0xec, 0x71, 0xc0, 0x93, 0x27, 0x18, 0x52, 0x56, 0x18, 0x22, 0x27,
	0x32, 0x86, 0x14, 0x6c, 0x5e, 0x9f, 0xd3, 0x60, 0x34, 0xa2, 0x7e, 0x2c, 0x90, 0x95, 0xbc, 0x3e,
	0x8e, 0xf0, 0x4b, 0x60, 0xd1, 0xe4, 0x4c, 0xe8, 0xb0, 0xf4, 0x50, 0x95, 0x09, 0x9c, 0x50, 0xd2,
	0x4d, 0x54, 0x03, 0x9b, 0xa8, 0xdc, 0x75, 0x63, 0x8f, 0x02, 0x05, 0xaa, 0xed, 0xea, 0x6c, 0x6a,
	0x96, 0x63, 0xee, 0x20, 0xe2, 0x23, 0xb6, 0x3c, 0xf7, 0x9d, 0xa0, 0xef, 0xfa, 0x43, 0xa8, 0xfa,
	0x66, 0xb6, 0x25, 0x95, 0x6e, 0xa2, 0x1a, 0x22, 0x78, 0xcf, 0xa3, 0x8e, 0x0c, 0x1e, 0xa9, 0xc1,
	0x83, 0x3f, 0x0f, 0x5e, 0x31, 0x79, 0x11, 0xde, 0xd9, 0x8c, 0xd3, 0xc5, 0xd0, 0x73, 0x72, 0xdd,
	0xda, 0x0c, 0x38, 0x41, 0xb2, 0x11, 0x0f, 0xe9, 0x9d, 0xcd, 0xe4, 0x19, 0x46, 0x2d, 0xbf, 0x25,
	0x5f, 0x21, 0xf7, 0x24, 0xaa, 0x81, 0x5f, 0x23, 0xfd, 0x8c, 0x32, 0x27, 0x72, 0xc3, 0xd8, 0x0d,
	0x7c, 0xa3, 0x0e, 0x77, 0x05, 0x48, 0x3f, 0x77, 0x13, 0xd5, 0xb0, 0x06, 0xa8, 0x06, 0x84, 0xbb,
	0xa0, 0xb4, 0x4f, 0xe8, 0x17, 0x7e, 0xe8, 0xa5, 0x1d, 0x53, 0x16, 0x77, 0xdd, 0x11, 0x05, 0x0e,
	0xca, 0x43, 0x3d, 0xf0, 0xf6, 0x62, 0x77, 0x44, 0x89, 0x6a, 0x28, 0x42, 0xb5, 0xb6, 0x5c, 0xa8,
	0xac, 0x2b, 0x54, 0x57, 0xce, 0x61, 0x21, 0xfe, 0x51, 0xd2, 0xfe, 0xd2, 0x65, 0xb1, 0x51, 0x6a,
	0x69, 0x7b, 0xfa, 0xe1, 0x33, 0xc9, 0xe1, 0xac, 0x1d, 0xda, 0x5b, 0xb3, 0xa9, 0x89, 0x24, 0xe7,
	0xfd, 0x41, 0x40, 0x94, 0xb1, 0xf5, 0xd7, 0x1a, 0xda, 0xba, 0x0e, 0xbd, 0xc0, 0xee, 0xc3, 0x7a,
	0x1e, 0xfc, 0xdc, 0xfd, 0x4b, 0x8f, 0xdf, 0x3f, 0x27, 0xc6, 0xda, 0x12, 0x62, 0xbc, 0x42, 0x9b,
	0xb0, 0x7f, 0xd7, 0x1e, 0x1a, 0x5a, 0x4b, 0x4b, 0x5b, 0x41, 0x04, 0x12, 0xdb, 0x43, 0x92, 0x0f,
	0xa1, 0x15, 0x5c, 0x8f, 0x9e, 0xff, 0x1e, 0x53, 0x9f, 0xf1, 0x08, 0x44, 0xef, 0x88, 0x56, 0x70,
	0x3d, 0xda, 0xa3, 0xe9, 0x0c, 0x99, 0xb3, 0x95, 0x2c, 0x96, 0x57, 0xc8, 0x7d, 0x26, 0x0f, 0x7d,
	0xa9, 0x93, 0x4b, 0xe4, 0xc1, 0xfa, 0xb3, 0x84, 0x1a, 0x85, 0xe4, 0xb0, 0x10, 0xae, 0x1a, 0xdc,
	0xd1, 0x34, 0x2f, 0xe2, 0xaa, 0xdc, 0x41, 0xc4, 0x87, 0x3f, 0x10, 0x84, 0xb2, 0x20, 0x89, 0x1c,
	0xfa, 0x9e, 0x4e, 0x64, 0x46, 0xe0, 0x81, 0x88, 0xa4, 0xbb, 0x77, 0x47, 0x27, 0xa4, 0x60, 0xa9,
	0x21, 0x69, 0x2b, 0x43, 0xaa, 0x23, 0xfd, 0x2c, 0xb8, 0xf7, 0x79, 0x4c, 0x84, 0x7e, 0xb1, 0x0e,
	0x50, 0x8d, 0x9b, 0x97, 0x60, 0x3e, 0x21, 0x3a, 0xeb, 0x07, 0xb4, 0xfd, 0x13, 0x8d, 0x73, 0x6e,
	0x4c, 0x3a, 0x40, 0x58, 0xe5, 0xfc, 0x95, 0x8a, 0x69, 0x75, 0xd0, 0xce, 0x43, 0x3c, 0x0b, 0xf1,
	0x6b, 0x54, 0x06, 0x27, 0xc0, 0x17, 0x91, 0x10, 0x42, 0x01, 0x27, 0x11, 0x1f, 0xeb, 0x37, 0x54,
	0x23, 0xf4, 0xc6, 0x76, 0xee, 0x7e, 0xf6, 0x29, 0x8f, 0x21, 0x23, 0x51, 0x69, 0x39, 0x89, 0x32,
	0x3d, 0x5d, 0x5b, 0xad, 0xa7, 0x56, 0x03, 0xd5, 0x95, 0xcd, 0x59, 0x68, 0xfd, 0x51, 0x4a, 0x8f,
	0xeb, 0xde, 0x03, 0xcd, 0x77, 0x0a, 0xc7, 0x11, 0x61, 0xe0, 0xd6, 0x7c, 0xf5, 0xb4, 0xbd, 0x2a,
	0x51, 0x5d, 0x18, 0xa3, 0xf5, 0xee, 0x24, 0xa4, 0x82, 0xc6, 0x04, 0xc6, 0xd8, 0xc8, 0xd3, 0x07,
	0x64, 0x25, 0xa9, 0xc9, 0x67, 0x7e, 0x49, 0x6c, 0xcf, 0x8d, 0x27, 0x46, 0xb9, 0xa5, 0xed, 0x69,
	0x24, 0x35, 0xf3, 0x08, 0x21, 0x1e, 0x16, 0x5a, 0xc7, 0x68, 0x4b, 0xbe, 0xcc, 0xbc, 0x9b, 0x79,
	0x88, 0x4f, 0xfa, 0xf5, 0x62, 0x9d, 0xa1, 0x46, 0x01, 0x57, 0xac, 0x86, 0xf6, 0xc4, 0x6a, 0x78,
	0xc8, 0xf8, 0x48, 0xed, 0xc8, 0xb9, 0x85, 0x45, 0xed, 0x49, 0xda, 0xae, 0x3c, 0x0e, 0xb5, 0x7b,
	0x4b, 0x79, 0xe2, 0x17, 0x76, 0xef, 0xd3, 0x84, 0xec, 0x57, 0xf4, 0xbf, 0x25, 0xa7, 0xb1, 0x10,
	0xbf, 0x7d, 0x2c, 0xfa, 0x55, 0x82, 0x76, 0x8e, 0xb6, 0x3b, 0x7e, 0xe4, 0xa8, 0x2f, 0x22, 0xbf,
	0x82, 0x31, 0x47, 0xf0, 0xbc, 0x42, 0x3b, 0xa8, 0x2c, 0x9e, 0x1e, 0x1e, 0xaf, 0x46, 0x84, 0x61,
	0xbd, 0x40, 0x3b, 0x0f, 0xb7, 0x61, 0xa1, 0xf5, 0x86, 0xcb, 0x65, 0xdf, 0x8e, 0x69, 0x26, 0x97,
	0x5f, 0x3f, 0xc2, 0x7c, 0x22, 0xa6, 0xad, 0xe7, 0x5c, 0x4b, 0x14, 0x24, 0x0b, 0xad, 0x09, 0xaa,
	0x75, 0x7c, 0x27, 0xe2, 0x6a, 0xd7, 0x97, 0x1d, 0x00, 0x63, 0xb5, 0x03, 0x06, 0x30, 0x29, 0x3e,
	0x7c, 0xc1, 0x27, 0xdb, 0x4b, 0x84, 0xce, 0x6a, 0xb2, 0x8a, 0xdc, 0x41, 0xc4, 0xe7, 0xe9, 0x3a,
	0xd2, 0x40, 0x75, 0xe5, 0x68, 0x16, 0x1e, 0xfe, 0x5d, 0x96, 0x6f, 0xd8, 0x47, 0x1a, 0x8d, 0x5d,
	0x87, 0xe2, 0x63, 0xf9, 0xb4, 0xf0, 0xb7, 0x06, 0x6f, 0xab, 0xb7, 0x92, 0xaf, 0x5c, 0x73, 0xe7,
	0xa1, 0x93, 0x85, 0xf8, 0x7b, 0xa4, 0x2b, 0x9a, 0x89, 0x77, 0xd3, 0x9f, 0x54, 0x85, 0x47, 0xa6,
	0xf9, 0x62, 0x91, 0x9b, 0x85, 0xf8, 0x0d, 0xaa, 0xa7, 0x82, 0x26, 0xf0, 0x58, 0x2e, 0x54, 0x54,
	0xaf, 0xb9, 0xad, 0xf8, 0x32, 0xe9, 0x7b, 0x8f, 0x9e, 0xcd, 0x2b, 0x13, 0x6e, 0xca, 0x85, 0x0b,
	0x24, 0xaf, 0xf9, 0xff, 0xa5, 0x73, 0x10, 0x86, 0x7e, 0x6a, 0x7b, 0x9e, 0x14, 0x90, 0xec, 0xfa,
	0xaa, 0x5e, 0x65, 0xd7, 0x2f, 0xe8, 0x8c, 0x8a, 0xec, 0xde, 0x07, 0x73, 0x48, 0x21, 0x3d, 0x73,
	0x48, 0xd9, 0xff, 0x3c, 0x71, 0x4a, 0x1f, 0x67, 0x89, 0x2b, 0x6a, 0x42, 0x96, 0xb8, 0xf9, 0x96,
	0xff, 0x8c, 0x76, 0x17, 0x76, 0x14, 0x36, 0x25, 0x60, 0x59, 0x77, 0x37, 0x5b, 0xab, 0x17, 0x88,
	0xd4, 0xce, 0x37, 0x43, 0x96, 0xda, 0x05, 0xcd, 0x96, 0xa5, 0x76, 0x51, 0x07, 0x09, 0x7e, 0x64,
	0x7d, 0xa0, 0xf0, 0x43, 0xed, 0x2a, 0x85, 0x1f, 0x85, 0x96, 0xe1, 0xac, 0xcc, 0x78, 0x9b, 0x25,
	0x57, 0x6d, 0xa2, 0x2c, 0xb9, 0x05, 0x7a, 0xb7, 0xeb, 0x9f, 0xf5, 0xfd, 0x83, 0xb7, 0x30, 0x73,
	0x12, 0xba, 0x37, 0x15, 0xf8, 0xaf, 0x78, 0xf4, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x68,
	0x4c, 0x4a, 0x70, 0x0e, 0x00, 0x00,
}
