// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base.proto

package baseApi

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserLoginReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,json=user_name,proto3" json:"user_name"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}
func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,json=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResp) Reset()         { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()    {}
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}
func (m *UserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResp.Unmarshal(m, b)
}
func (m *UserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResp.Marshal(b, m, deterministic)
}
func (m *UserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResp.Merge(m, src)
}
func (m *UserLoginResp) XXX_Size() int {
	return xxx_messageInfo_UserLoginResp.Size(m)
}
func (m *UserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResp proto.InternalMessageInfo

func (m *UserLoginResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserLoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserRegisterReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,json=user_name,proto3" json:"user_name"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterReq) Reset()         { *m = UserRegisterReq{} }
func (m *UserRegisterReq) String() string { return proto.CompactTextString(m) }
func (*UserRegisterReq) ProtoMessage()    {}
func (*UserRegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}
func (m *UserRegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterReq.Unmarshal(m, b)
}
func (m *UserRegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterReq.Marshal(b, m, deterministic)
}
func (m *UserRegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterReq.Merge(m, src)
}
func (m *UserRegisterReq) XXX_Size() int {
	return xxx_messageInfo_UserRegisterReq.Size(m)
}
func (m *UserRegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterReq proto.InternalMessageInfo

func (m *UserRegisterReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserRegisterResp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,json=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResp) Reset()         { *m = UserRegisterResp{} }
func (m *UserRegisterResp) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResp) ProtoMessage()    {}
func (*UserRegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{3}
}
func (m *UserRegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResp.Unmarshal(m, b)
}
func (m *UserRegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResp.Marshal(b, m, deterministic)
}
func (m *UserRegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResp.Merge(m, src)
}
func (m *UserRegisterResp) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResp.Size(m)
}
func (m *UserRegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResp proto.InternalMessageInfo

func (m *UserRegisterResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRegisterResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoReq) Reset()         { *m = UserInfoReq{} }
func (m *UserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoReq) ProtoMessage()    {}
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{4}
}
func (m *UserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReq.Unmarshal(m, b)
}
func (m *UserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReq.Marshal(b, m, deterministic)
}
func (m *UserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReq.Merge(m, src)
}
func (m *UserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoReq.Size(m)
}
func (m *UserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReq proto.InternalMessageInfo

func (m *UserInfoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,json=user_name,proto3" json:"user_name"`
	FollowCount          int64    `protobuf:"varint,3,opt,name=FollowCount,json=follow_count,proto3" json:"follow_count"`
	FollowerCount        int64    `protobuf:"varint,4,opt,name=FollowerCount,json=follower_count,proto3" json:"follower_count"`
	IsFollow             int64    `protobuf:"varint,5,opt,name=IsFollow,json=is_follow,proto3" json:"is_follow"`
	Avatar               string   `protobuf:"bytes,6,opt,name=Avatar,json=avatar,proto3" json:"avatar"`
	PublishNum           int64    `protobuf:"varint,7,opt,name=PublishNum,json=publish_num,proto3" json:"publish_num"`
	FavouriteNum         int64    `protobuf:"varint,8,opt,name=FavouriteNum,json=favourite_num,proto3" json:"favourite_num"`
	LikeNum              int64    `protobuf:"varint,9,opt,name=LikeNum,json=like_num,proto3" json:"like_num"`
	ReceivedLikeNum      int64    `protobuf:"varint,10,opt,name=ReceivedLikeNum,json=received_like_num,proto3" json:"received_like_num"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{5}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetFollowCount() int64 {
	if m != nil {
		return m.FollowCount
	}
	return 0
}

func (m *UserInfo) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *UserInfo) GetIsFollow() int64 {
	if m != nil {
		return m.IsFollow
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetPublishNum() int64 {
	if m != nil {
		return m.PublishNum
	}
	return 0
}

func (m *UserInfo) GetFavouriteNum() int64 {
	if m != nil {
		return m.FavouriteNum
	}
	return 0
}

func (m *UserInfo) GetLikeNum() int64 {
	if m != nil {
		return m.LikeNum
	}
	return 0
}

func (m *UserInfo) GetReceivedLikeNum() int64 {
	if m != nil {
		return m.ReceivedLikeNum
	}
	return 0
}

type UserInfoResp struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=User,json=user,proto3" json:"user"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoResp) Reset()         { *m = UserInfoResp{} }
func (m *UserInfoResp) String() string { return proto.CompactTextString(m) }
func (*UserInfoResp) ProtoMessage()    {}
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{6}
}
func (m *UserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResp.Unmarshal(m, b)
}
func (m *UserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResp.Marshal(b, m, deterministic)
}
func (m *UserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResp.Merge(m, src)
}
func (m *UserInfoResp) XXX_Size() int {
	return xxx_messageInfo_UserInfoResp.Size(m)
}
func (m *UserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResp proto.InternalMessageInfo

func (m *UserInfoResp) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type VideoInfo struct {
	VideoID              string    `protobuf:"bytes,1,opt,name=VideoID,json=video_id,proto3" json:"video_id"`
	Author               *UserInfo `protobuf:"bytes,2,opt,name=Author,json=author,proto3" json:"author"`
	PlayUrl              string    `protobuf:"bytes,3,opt,name=PlayUrl,json=play_url,proto3" json:"play_url"`
	CoverUrl             string    `protobuf:"bytes,4,opt,name=CoverUrl,json=cover_url,proto3" json:"cover_url"`
	FavoriteCount        int64     `protobuf:"varint,5,opt,name=FavoriteCount,json=favorite_count,proto3" json:"favorite_count"`
	CommentCount         int64     `protobuf:"varint,6,opt,name=CommentCount,json=comment_count,proto3" json:"comment_count"`
	IsFavorite           int64     `protobuf:"varint,7,opt,name=IsFavorite,json=is_favorite,proto3" json:"is_favorite"`
	Title                string    `protobuf:"bytes,8,opt,name=Title,json=title,proto3" json:"title"`
	IsEncoding           bool      `protobuf:"varint,9,opt,name=IsEncoding,json=is_encoding,proto3" json:"is_encoding"`
	CollectCount         int64     `protobuf:"varint,10,opt,name=CollectCount,json=collect_count,proto3" json:"collect_count"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VideoInfo) Reset()         { *m = VideoInfo{} }
func (m *VideoInfo) String() string { return proto.CompactTextString(m) }
func (*VideoInfo) ProtoMessage()    {}
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{7}
}
func (m *VideoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoInfo.Unmarshal(m, b)
}
func (m *VideoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoInfo.Marshal(b, m, deterministic)
}
func (m *VideoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoInfo.Merge(m, src)
}
func (m *VideoInfo) XXX_Size() int {
	return xxx_messageInfo_VideoInfo.Size(m)
}
func (m *VideoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VideoInfo proto.InternalMessageInfo

func (m *VideoInfo) GetVideoID() string {
	if m != nil {
		return m.VideoID
	}
	return ""
}

func (m *VideoInfo) GetAuthor() *UserInfo {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *VideoInfo) GetPlayUrl() string {
	if m != nil {
		return m.PlayUrl
	}
	return ""
}

func (m *VideoInfo) GetCoverUrl() string {
	if m != nil {
		return m.CoverUrl
	}
	return ""
}

func (m *VideoInfo) GetFavoriteCount() int64 {
	if m != nil {
		return m.FavoriteCount
	}
	return 0
}

func (m *VideoInfo) GetCommentCount() int64 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *VideoInfo) GetIsFavorite() int64 {
	if m != nil {
		return m.IsFavorite
	}
	return 0
}

func (m *VideoInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoInfo) GetIsEncoding() bool {
	if m != nil {
		return m.IsEncoding
	}
	return false
}

func (m *VideoInfo) GetCollectCount() int64 {
	if m != nil {
		return m.CollectCount
	}
	return 0
}

type CommentInfo struct {
	CommentId            string    `protobuf:"bytes,1,opt,name=CommentId,json=comment_id,proto3" json:"comment_id"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=User,json=user,proto3" json:"user"`
	VideoId              string    `protobuf:"bytes,3,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	Content              string    `protobuf:"bytes,4,opt,name=Content,json=content,proto3" json:"content"`
	PublishDate          int64     `protobuf:"varint,5,opt,name=PublishDate,json=publish_date,proto3" json:"publish_date"`
	Replies              int64     `protobuf:"varint,6,opt,name=Replies,json=replies,proto3" json:"replies"`
	LikeCount            int64     `protobuf:"varint,7,opt,name=LikeCount,json=like_count,proto3" json:"like_count"`
	HasLike              int64     `protobuf:"varint,8,opt,name=HasLike,json=has_like,proto3" json:"has_like"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommentInfo) Reset()         { *m = CommentInfo{} }
func (m *CommentInfo) String() string { return proto.CompactTextString(m) }
func (*CommentInfo) ProtoMessage()    {}
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{8}
}
func (m *CommentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentInfo.Unmarshal(m, b)
}
func (m *CommentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentInfo.Marshal(b, m, deterministic)
}
func (m *CommentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentInfo.Merge(m, src)
}
func (m *CommentInfo) XXX_Size() int {
	return xxx_messageInfo_CommentInfo.Size(m)
}
func (m *CommentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CommentInfo proto.InternalMessageInfo

func (m *CommentInfo) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *CommentInfo) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CommentInfo) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *CommentInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CommentInfo) GetPublishDate() int64 {
	if m != nil {
		return m.PublishDate
	}
	return 0
}

func (m *CommentInfo) GetReplies() int64 {
	if m != nil {
		return m.Replies
	}
	return 0
}

func (m *CommentInfo) GetLikeCount() int64 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *CommentInfo) GetHasLike() int64 {
	if m != nil {
		return m.HasLike
	}
	return 0
}

type CreateCommentReq struct {
	VideoId              string   `protobuf:"bytes,1,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	ActionType           int64    `protobuf:"varint,2,opt,name=ActionType,json=action_type,proto3" json:"action_type"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,json=content,proto3" json:"content"`
	CommentId            string   `protobuf:"bytes,4,opt,name=CommentId,json=comment_id,proto3" json:"comment_id"`
	UserID               string   `protobuf:"bytes,5,opt,name=UserID,json=user_id,proto3" json:"user_id"`
	RootId               string   `protobuf:"bytes,6,opt,name=RootId,json=root_id,proto3" json:"root_id"`
	ParentId             string   `protobuf:"bytes,7,opt,name=ParentId,json=parent_id,proto3" json:"parent_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentReq) Reset()         { *m = CreateCommentReq{} }
func (m *CreateCommentReq) String() string { return proto.CompactTextString(m) }
func (*CreateCommentReq) ProtoMessage()    {}
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{9}
}
func (m *CreateCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentReq.Unmarshal(m, b)
}
func (m *CreateCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentReq.Marshal(b, m, deterministic)
}
func (m *CreateCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentReq.Merge(m, src)
}
func (m *CreateCommentReq) XXX_Size() int {
	return xxx_messageInfo_CreateCommentReq.Size(m)
}
func (m *CreateCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentReq proto.InternalMessageInfo

func (m *CreateCommentReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *CreateCommentReq) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

func (m *CreateCommentReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateCommentReq) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *CreateCommentReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateCommentReq) GetRootId() string {
	if m != nil {
		return m.RootId
	}
	return ""
}

func (m *CreateCommentReq) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

type CreateCommentResp struct {
	CommentId            string   `protobuf:"bytes,1,opt,name=CommentId,json=comment_id,proto3" json:"comment_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentResp) Reset()         { *m = CreateCommentResp{} }
func (m *CreateCommentResp) String() string { return proto.CompactTextString(m) }
func (*CreateCommentResp) ProtoMessage()    {}
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{10}
}
func (m *CreateCommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentResp.Unmarshal(m, b)
}
func (m *CreateCommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentResp.Marshal(b, m, deterministic)
}
func (m *CreateCommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentResp.Merge(m, src)
}
func (m *CreateCommentResp) XXX_Size() int {
	return xxx_messageInfo_CreateCommentResp.Size(m)
}
func (m *CreateCommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentResp proto.InternalMessageInfo

func (m *CreateCommentResp) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

type CommentListReq struct {
	VideoId              string   `protobuf:"bytes,1,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,json=token,proto3" json:"token"`
	ParentID             string   `protobuf:"bytes,3,opt,name=ParentID,json=parent_id,proto3" json:"parent_id"`
	RootID               string   `protobuf:"bytes,4,opt,name=RootID,json=root_id,proto3" json:"root_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentListReq) Reset()         { *m = CommentListReq{} }
func (m *CommentListReq) String() string { return proto.CompactTextString(m) }
func (*CommentListReq) ProtoMessage()    {}
func (*CommentListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{11}
}
func (m *CommentListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentListReq.Unmarshal(m, b)
}
func (m *CommentListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentListReq.Marshal(b, m, deterministic)
}
func (m *CommentListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentListReq.Merge(m, src)
}
func (m *CommentListReq) XXX_Size() int {
	return xxx_messageInfo_CommentListReq.Size(m)
}
func (m *CommentListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentListReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommentListReq proto.InternalMessageInfo

func (m *CommentListReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *CommentListReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CommentListReq) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *CommentListReq) GetRootID() string {
	if m != nil {
		return m.RootID
	}
	return ""
}

type CommentListResp struct {
	List                 []*CommentInfo `protobuf:"bytes,1,rep,name=List,json=comment_info,proto3" json:"comment_info"`
	HasNext              int64          `protobuf:"varint,7,opt,name=HasNext,json=has_next,proto3" json:"has_next"`
	NextPageToken        string         `protobuf:"bytes,8,opt,name=NextPageToken,json=next_page_token,proto3" json:"next_page_token"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommentListResp) Reset()         { *m = CommentListResp{} }
func (m *CommentListResp) String() string { return proto.CompactTextString(m) }
func (*CommentListResp) ProtoMessage()    {}
func (*CommentListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{12}
}
func (m *CommentListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentListResp.Unmarshal(m, b)
}
func (m *CommentListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentListResp.Marshal(b, m, deterministic)
}
func (m *CommentListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentListResp.Merge(m, src)
}
func (m *CommentListResp) XXX_Size() int {
	return xxx_messageInfo_CommentListResp.Size(m)
}
func (m *CommentListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentListResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommentListResp proto.InternalMessageInfo

func (m *CommentListResp) GetList() []*CommentInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *CommentListResp) GetHasNext() int64 {
	if m != nil {
		return m.HasNext
	}
	return 0
}

func (m *CommentListResp) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type LikeVideoActionReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	VideoId              string   `protobuf:"bytes,2,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	ActionType           int64    `protobuf:"varint,3,opt,name=ActionType,json=action_type,proto3" json:"action_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeVideoActionReq) Reset()         { *m = LikeVideoActionReq{} }
func (m *LikeVideoActionReq) String() string { return proto.CompactTextString(m) }
func (*LikeVideoActionReq) ProtoMessage()    {}
func (*LikeVideoActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{13}
}
func (m *LikeVideoActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeVideoActionReq.Unmarshal(m, b)
}
func (m *LikeVideoActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeVideoActionReq.Marshal(b, m, deterministic)
}
func (m *LikeVideoActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeVideoActionReq.Merge(m, src)
}
func (m *LikeVideoActionReq) XXX_Size() int {
	return xxx_messageInfo_LikeVideoActionReq.Size(m)
}
func (m *LikeVideoActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeVideoActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_LikeVideoActionReq proto.InternalMessageInfo

func (m *LikeVideoActionReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LikeVideoActionReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *LikeVideoActionReq) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type LikeVideoActionResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeVideoActionResp) Reset()         { *m = LikeVideoActionResp{} }
func (m *LikeVideoActionResp) String() string { return proto.CompactTextString(m) }
func (*LikeVideoActionResp) ProtoMessage()    {}
func (*LikeVideoActionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{14}
}
func (m *LikeVideoActionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeVideoActionResp.Unmarshal(m, b)
}
func (m *LikeVideoActionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeVideoActionResp.Marshal(b, m, deterministic)
}
func (m *LikeVideoActionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeVideoActionResp.Merge(m, src)
}
func (m *LikeVideoActionResp) XXX_Size() int {
	return xxx_messageInfo_LikeVideoActionResp.Size(m)
}
func (m *LikeVideoActionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeVideoActionResp.DiscardUnknown(m)
}

var xxx_messageInfo_LikeVideoActionResp proto.InternalMessageInfo

type VideoLikeListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoLikeListReq) Reset()         { *m = VideoLikeListReq{} }
func (m *VideoLikeListReq) String() string { return proto.CompactTextString(m) }
func (*VideoLikeListReq) ProtoMessage()    {}
func (*VideoLikeListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{15}
}
func (m *VideoLikeListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoLikeListReq.Unmarshal(m, b)
}
func (m *VideoLikeListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoLikeListReq.Marshal(b, m, deterministic)
}
func (m *VideoLikeListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoLikeListReq.Merge(m, src)
}
func (m *VideoLikeListReq) XXX_Size() int {
	return xxx_messageInfo_VideoLikeListReq.Size(m)
}
func (m *VideoLikeListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoLikeListReq.DiscardUnknown(m)
}

var xxx_messageInfo_VideoLikeListReq proto.InternalMessageInfo

func (m *VideoLikeListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type VideoLikeListResp struct {
	VideoList            []*VideoInfo `protobuf:"bytes,1,rep,name=VideoList,json=video_info,proto3" json:"video_info"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VideoLikeListResp) Reset()         { *m = VideoLikeListResp{} }
func (m *VideoLikeListResp) String() string { return proto.CompactTextString(m) }
func (*VideoLikeListResp) ProtoMessage()    {}
func (*VideoLikeListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{16}
}
func (m *VideoLikeListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoLikeListResp.Unmarshal(m, b)
}
func (m *VideoLikeListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoLikeListResp.Marshal(b, m, deterministic)
}
func (m *VideoLikeListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoLikeListResp.Merge(m, src)
}
func (m *VideoLikeListResp) XXX_Size() int {
	return xxx_messageInfo_VideoLikeListResp.Size(m)
}
func (m *VideoLikeListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoLikeListResp.DiscardUnknown(m)
}

var xxx_messageInfo_VideoLikeListResp proto.InternalMessageInfo

func (m *VideoLikeListResp) GetVideoList() []*VideoInfo {
	if m != nil {
		return m.VideoList
	}
	return nil
}

type LikeCommentReq struct {
	CommentID            string   `protobuf:"bytes,1,opt,name=CommentID,json=comment_id,proto3" json:"comment_id"`
	ActionType           int64    `protobuf:"varint,2,opt,name=ActionType,json=action_type,proto3" json:"action_type"`
	UserId               string   `protobuf:"bytes,3,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeCommentReq) Reset()         { *m = LikeCommentReq{} }
func (m *LikeCommentReq) String() string { return proto.CompactTextString(m) }
func (*LikeCommentReq) ProtoMessage()    {}
func (*LikeCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{17}
}
func (m *LikeCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeCommentReq.Unmarshal(m, b)
}
func (m *LikeCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeCommentReq.Marshal(b, m, deterministic)
}
func (m *LikeCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeCommentReq.Merge(m, src)
}
func (m *LikeCommentReq) XXX_Size() int {
	return xxx_messageInfo_LikeCommentReq.Size(m)
}
func (m *LikeCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_LikeCommentReq proto.InternalMessageInfo

func (m *LikeCommentReq) GetCommentID() string {
	if m != nil {
		return m.CommentID
	}
	return ""
}

func (m *LikeCommentReq) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

func (m *LikeCommentReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LikeCommentResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeCommentResp) Reset()         { *m = LikeCommentResp{} }
func (m *LikeCommentResp) String() string { return proto.CompactTextString(m) }
func (*LikeCommentResp) ProtoMessage()    {}
func (*LikeCommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{18}
}
func (m *LikeCommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeCommentResp.Unmarshal(m, b)
}
func (m *LikeCommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeCommentResp.Marshal(b, m, deterministic)
}
func (m *LikeCommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeCommentResp.Merge(m, src)
}
func (m *LikeCommentResp) XXX_Size() int {
	return xxx_messageInfo_LikeCommentResp.Size(m)
}
func (m *LikeCommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeCommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_LikeCommentResp proto.InternalMessageInfo

type FollowListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowListReq) Reset()         { *m = FollowListReq{} }
func (m *FollowListReq) String() string { return proto.CompactTextString(m) }
func (*FollowListReq) ProtoMessage()    {}
func (*FollowListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{19}
}
func (m *FollowListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowListReq.Unmarshal(m, b)
}
func (m *FollowListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowListReq.Marshal(b, m, deterministic)
}
func (m *FollowListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowListReq.Merge(m, src)
}
func (m *FollowListReq) XXX_Size() int {
	return xxx_messageInfo_FollowListReq.Size(m)
}
func (m *FollowListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowListReq.DiscardUnknown(m)
}

var xxx_messageInfo_FollowListReq proto.InternalMessageInfo

func (m *FollowListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type FollowListResp struct {
	User                 []*UserInfo `protobuf:"bytes,1,rep,name=User,json=user_info,proto3" json:"user_info"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FollowListResp) Reset()         { *m = FollowListResp{} }
func (m *FollowListResp) String() string { return proto.CompactTextString(m) }
func (*FollowListResp) ProtoMessage()    {}
func (*FollowListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{20}
}
func (m *FollowListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowListResp.Unmarshal(m, b)
}
func (m *FollowListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowListResp.Marshal(b, m, deterministic)
}
func (m *FollowListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowListResp.Merge(m, src)
}
func (m *FollowListResp) XXX_Size() int {
	return xxx_messageInfo_FollowListResp.Size(m)
}
func (m *FollowListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowListResp.DiscardUnknown(m)
}

var xxx_messageInfo_FollowListResp proto.InternalMessageInfo

func (m *FollowListResp) GetUser() []*UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type FollowerListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowerListReq) Reset()         { *m = FollowerListReq{} }
func (m *FollowerListReq) String() string { return proto.CompactTextString(m) }
func (*FollowerListReq) ProtoMessage()    {}
func (*FollowerListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{21}
}
func (m *FollowerListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerListReq.Unmarshal(m, b)
}
func (m *FollowerListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerListReq.Marshal(b, m, deterministic)
}
func (m *FollowerListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerListReq.Merge(m, src)
}
func (m *FollowerListReq) XXX_Size() int {
	return xxx_messageInfo_FollowerListReq.Size(m)
}
func (m *FollowerListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerListReq.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerListReq proto.InternalMessageInfo

func (m *FollowerListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type FollowerListResp struct {
	User                 []*UserInfo `protobuf:"bytes,1,rep,name=User,json=user_info,proto3" json:"user_info"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FollowerListResp) Reset()         { *m = FollowerListResp{} }
func (m *FollowerListResp) String() string { return proto.CompactTextString(m) }
func (*FollowerListResp) ProtoMessage()    {}
func (*FollowerListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{22}
}
func (m *FollowerListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerListResp.Unmarshal(m, b)
}
func (m *FollowerListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerListResp.Marshal(b, m, deterministic)
}
func (m *FollowerListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerListResp.Merge(m, src)
}
func (m *FollowerListResp) XXX_Size() int {
	return xxx_messageInfo_FollowerListResp.Size(m)
}
func (m *FollowerListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerListResp.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerListResp proto.InternalMessageInfo

func (m *FollowerListResp) GetUser() []*UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type FollowReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	ToUserId             string   `protobuf:"bytes,2,opt,name=ToUserId,json=to_user_id,proto3" json:"to_user_id"`
	ActionType           int64    `protobuf:"varint,3,opt,name=ActionType,json=action_type,proto3" json:"action_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowReq) Reset()         { *m = FollowReq{} }
func (m *FollowReq) String() string { return proto.CompactTextString(m) }
func (*FollowReq) ProtoMessage()    {}
func (*FollowReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{23}
}
func (m *FollowReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowReq.Unmarshal(m, b)
}
func (m *FollowReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowReq.Marshal(b, m, deterministic)
}
func (m *FollowReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowReq.Merge(m, src)
}
func (m *FollowReq) XXX_Size() int {
	return xxx_messageInfo_FollowReq.Size(m)
}
func (m *FollowReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowReq.DiscardUnknown(m)
}

var xxx_messageInfo_FollowReq proto.InternalMessageInfo

func (m *FollowReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FollowReq) GetToUserId() string {
	if m != nil {
		return m.ToUserId
	}
	return ""
}

func (m *FollowReq) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type FollowResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowResp) Reset()         { *m = FollowResp{} }
func (m *FollowResp) String() string { return proto.CompactTextString(m) }
func (*FollowResp) ProtoMessage()    {}
func (*FollowResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{24}
}
func (m *FollowResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowResp.Unmarshal(m, b)
}
func (m *FollowResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowResp.Marshal(b, m, deterministic)
}
func (m *FollowResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowResp.Merge(m, src)
}
func (m *FollowResp) XXX_Size() int {
	return xxx_messageInfo_FollowResp.Size(m)
}
func (m *FollowResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowResp.DiscardUnknown(m)
}

var xxx_messageInfo_FollowResp proto.InternalMessageInfo

type CollectVideoActionReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	VideoId              string   `protobuf:"bytes,2,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	ActionType           int64    `protobuf:"varint,3,opt,name=ActionType,json=action_type,proto3" json:"action_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectVideoActionReq) Reset()         { *m = CollectVideoActionReq{} }
func (m *CollectVideoActionReq) String() string { return proto.CompactTextString(m) }
func (*CollectVideoActionReq) ProtoMessage()    {}
func (*CollectVideoActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{25}
}
func (m *CollectVideoActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectVideoActionReq.Unmarshal(m, b)
}
func (m *CollectVideoActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectVideoActionReq.Marshal(b, m, deterministic)
}
func (m *CollectVideoActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectVideoActionReq.Merge(m, src)
}
func (m *CollectVideoActionReq) XXX_Size() int {
	return xxx_messageInfo_CollectVideoActionReq.Size(m)
}
func (m *CollectVideoActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectVideoActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_CollectVideoActionReq proto.InternalMessageInfo

func (m *CollectVideoActionReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CollectVideoActionReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *CollectVideoActionReq) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type CollectVideoActionResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectVideoActionResp) Reset()         { *m = CollectVideoActionResp{} }
func (m *CollectVideoActionResp) String() string { return proto.CompactTextString(m) }
func (*CollectVideoActionResp) ProtoMessage()    {}
func (*CollectVideoActionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{26}
}
func (m *CollectVideoActionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectVideoActionResp.Unmarshal(m, b)
}
func (m *CollectVideoActionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectVideoActionResp.Marshal(b, m, deterministic)
}
func (m *CollectVideoActionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectVideoActionResp.Merge(m, src)
}
func (m *CollectVideoActionResp) XXX_Size() int {
	return xxx_messageInfo_CollectVideoActionResp.Size(m)
}
func (m *CollectVideoActionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectVideoActionResp.DiscardUnknown(m)
}

var xxx_messageInfo_CollectVideoActionResp proto.InternalMessageInfo

type VideoCollectListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoCollectListReq) Reset()         { *m = VideoCollectListReq{} }
func (m *VideoCollectListReq) String() string { return proto.CompactTextString(m) }
func (*VideoCollectListReq) ProtoMessage()    {}
func (*VideoCollectListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{27}
}
func (m *VideoCollectListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoCollectListReq.Unmarshal(m, b)
}
func (m *VideoCollectListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoCollectListReq.Marshal(b, m, deterministic)
}
func (m *VideoCollectListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoCollectListReq.Merge(m, src)
}
func (m *VideoCollectListReq) XXX_Size() int {
	return xxx_messageInfo_VideoCollectListReq.Size(m)
}
func (m *VideoCollectListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoCollectListReq.DiscardUnknown(m)
}

var xxx_messageInfo_VideoCollectListReq proto.InternalMessageInfo

func (m *VideoCollectListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type VideoCollectListResp struct {
	VideoList            []*VideoInfo `protobuf:"bytes,1,rep,name=VideoList,json=video_info,proto3" json:"video_info"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VideoCollectListResp) Reset()         { *m = VideoCollectListResp{} }
func (m *VideoCollectListResp) String() string { return proto.CompactTextString(m) }
func (*VideoCollectListResp) ProtoMessage()    {}
func (*VideoCollectListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{28}
}
func (m *VideoCollectListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoCollectListResp.Unmarshal(m, b)
}
func (m *VideoCollectListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoCollectListResp.Marshal(b, m, deterministic)
}
func (m *VideoCollectListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoCollectListResp.Merge(m, src)
}
func (m *VideoCollectListResp) XXX_Size() int {
	return xxx_messageInfo_VideoCollectListResp.Size(m)
}
func (m *VideoCollectListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoCollectListResp.DiscardUnknown(m)
}

var xxx_messageInfo_VideoCollectListResp proto.InternalMessageInfo

func (m *VideoCollectListResp) GetVideoList() []*VideoInfo {
	if m != nil {
		return m.VideoList
	}
	return nil
}

func init() {
	proto.RegisterType((*UserLoginReq)(nil), "base.UserLoginReq")
	proto.RegisterType((*UserLoginResp)(nil), "base.UserLoginResp")
	proto.RegisterType((*UserRegisterReq)(nil), "base.UserRegisterReq")
	proto.RegisterType((*UserRegisterResp)(nil), "base.UserRegisterResp")
	proto.RegisterType((*UserInfoReq)(nil), "base.UserInfoReq")
	proto.RegisterType((*UserInfo)(nil), "base.UserInfo")
	proto.RegisterType((*UserInfoResp)(nil), "base.UserInfoResp")
	proto.RegisterType((*VideoInfo)(nil), "base.VideoInfo")
	proto.RegisterType((*CommentInfo)(nil), "base.CommentInfo")
	proto.RegisterType((*CreateCommentReq)(nil), "base.CreateCommentReq")
	proto.RegisterType((*CreateCommentResp)(nil), "base.CreateCommentResp")
	proto.RegisterType((*CommentListReq)(nil), "base.CommentListReq")
	proto.RegisterType((*CommentListResp)(nil), "base.CommentListResp")
	proto.RegisterType((*LikeVideoActionReq)(nil), "base.LikeVideoActionReq")
	proto.RegisterType((*LikeVideoActionResp)(nil), "base.LikeVideoActionResp")
	proto.RegisterType((*VideoLikeListReq)(nil), "base.VideoLikeListReq")
	proto.RegisterType((*VideoLikeListResp)(nil), "base.VideoLikeListResp")
	proto.RegisterType((*LikeCommentReq)(nil), "base.LikeCommentReq")
	proto.RegisterType((*LikeCommentResp)(nil), "base.LikeCommentResp")
	proto.RegisterType((*FollowListReq)(nil), "base.FollowListReq")
	proto.RegisterType((*FollowListResp)(nil), "base.FollowListResp")
	proto.RegisterType((*FollowerListReq)(nil), "base.FollowerListReq")
	proto.RegisterType((*FollowerListResp)(nil), "base.FollowerListResp")
	proto.RegisterType((*FollowReq)(nil), "base.FollowReq")
	proto.RegisterType((*FollowResp)(nil), "base.FollowResp")
	proto.RegisterType((*CollectVideoActionReq)(nil), "base.CollectVideoActionReq")
	proto.RegisterType((*CollectVideoActionResp)(nil), "base.CollectVideoActionResp")
	proto.RegisterType((*VideoCollectListReq)(nil), "base.VideoCollectListReq")
	proto.RegisterType((*VideoCollectListResp)(nil), "base.VideoCollectListResp")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 1444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdb, 0x6e, 0x1b, 0x37,
	0x13, 0x86, 0x0e, 0x96, 0xa5, 0x91, 0x6d, 0x59, 0x74, 0x9c, 0x5f, 0xd1, 0xff, 0x03, 0x1b, 0x2c,
	0xf2, 0x23, 0x46, 0x9b, 0x38, 0xa9, 0xd3, 0x26, 0x6d, 0xd2, 0x93, 0x0f, 0x0d, 0xe2, 0x22, 0x48,
	0x8d, 0xcd, 0x01, 0x68, 0x6f, 0x84, 0xb5, 0x44, 0xcb, 0x8b, 0x48, 0x22, 0xbb, 0x5c, 0x29, 0xf1,
	0x63, 0xf4, 0xa2, 0x68, 0x1f, 0xa2, 0x0f, 0x50, 0xb4, 0xef, 0xa2, 0x07, 0x58, 0xa0, 0xbd, 0xe8,
	0x13, 0x14, 0x1c, 0x92, 0xbb, 0x5c, 0x49, 0x8e, 0xa5, 0xa6, 0x05, 0x7a, 0x63, 0xcd, 0x0c, 0x67,
	0xc8, 0x39, 0x7c, 0x33, 0xe4, 0x1a, 0xe0, 0xd8, 0x17, 0x74, 0x9b, 0x87, 0x2c, 0x62, 0xa4, 0x28,
	0xe9, 0xe6, 0xcd, 0x6e, 0x10, 0x9d, 0x0e, 0x8f, 0xb7, 0xdb, 0xac, 0x7f, 0xab, 0xcb, 0xba, 0xec,
	0x16, 0x2e, 0x1e, 0x0f, 0x4f, 0x90, 0x43, 0x06, 0x29, 0x65, 0xe4, 0x76, 0x60, 0xe5, 0xb9, 0xa0,
	0xe1, 0x63, 0xd6, 0x0d, 0x06, 0x1e, 0xfd, 0x96, 0xbc, 0x03, 0x65, 0xc9, 0x3f, 0xf1, 0xfb, 0xb4,
	0x91, 0xbb, 0x9a, 0xdb, 0xaa, 0xec, 0xad, 0xc6, 0x63, 0xa7, 0x32, 0x14, 0x34, 0x6c, 0x0d, 0xfc,
	0x3e, 0xf5, 0x52, 0x92, 0x6c, 0x41, 0xf9, 0xc8, 0x17, 0xe2, 0x15, 0x0b, 0x3b, 0x8d, 0x3c, 0xea,
	0xae, 0xc4, 0x63, 0xa7, 0xcc, 0xb5, 0xcc, 0x4b, 0x28, 0xf7, 0x05, 0xac, 0x5a, 0xa7, 0x08, 0x4e,
	0xae, 0x41, 0x49, 0x0a, 0x0e, 0x3b, 0xfa, 0x90, 0x6a, 0x3c, 0x76, 0x96, 0x71, 0xe7, 0xa0, 0xe3,
	0x19, 0x82, 0x38, 0xb0, 0xf4, 0x8c, 0xbd, 0xa4, 0x03, 0xbd, 0x7b, 0x25, 0x1e, 0x3b, 0x4b, 0x91,
	0x14, 0x78, 0xea, 0xc7, 0xed, 0x42, 0x4d, 0x6e, 0xe3, 0xd1, 0x6e, 0x20, 0x22, 0xf9, 0xfb, 0x4f,
	0x05, 0xf0, 0x35, 0xac, 0x67, 0x0f, 0xfa, 0xfb, 0x62, 0xb8, 0x03, 0x55, 0xdc, 0x66, 0x70, 0xc2,
	0xa4, 0xff, 0x73, 0xed, 0xea, 0xfe, 0x51, 0x50, 0x61, 0x4a, 0xab, 0x39, 0x1d, 0xb1, 0x13, 0x93,
	0xbf, 0x20, 0x31, 0x77, 0xa0, 0xfa, 0x90, 0xf5, 0x7a, 0xec, 0xd5, 0x3e, 0x1b, 0x0e, 0xa2, 0x46,
	0xe1, 0x6a, 0x6e, 0xab, 0xb0, 0xb7, 0x1e, 0x8f, 0x9d, 0x95, 0x13, 0x14, 0xb7, 0xda, 0x52, 0xee,
	0x65, 0x38, 0xf2, 0x11, 0xac, 0x2a, 0x23, 0x1a, 0x2a, 0xb3, 0x22, 0x9a, 0x91, 0x78, 0xec, 0xac,
	0x9d, 0xe8, 0x05, 0x6d, 0x38, 0xc1, 0x4b, 0xdf, 0x0e, 0x85, 0x32, 0x6e, 0x2c, 0xa1, 0x15, 0xfa,
	0x16, 0x88, 0x96, 0x52, 0xf4, 0x52, 0x92, 0xb8, 0x50, 0xda, 0x1d, 0xf9, 0x91, 0x1f, 0x36, 0x4a,
	0x18, 0x05, 0xc4, 0x63, 0xa7, 0xe4, 0xa3, 0xc4, 0xd3, 0xbf, 0xe4, 0x36, 0xc0, 0xd1, 0xf0, 0xb8,
	0x17, 0x88, 0xd3, 0x27, 0xc3, 0x7e, 0x63, 0x19, 0x77, 0xac, 0xc5, 0x63, 0xa7, 0xca, 0x95, 0xb4,
	0x35, 0x18, 0xf6, 0x3d, 0x9b, 0x21, 0x77, 0x61, 0xe5, 0xa1, 0x3f, 0x62, 0xc3, 0x30, 0x88, 0xa8,
	0xb4, 0x29, 0xa3, 0x4d, 0x3d, 0x1e, 0x3b, 0xab, 0x27, 0x46, 0x8e, 0x56, 0x59, 0x96, 0x5c, 0x87,
	0xe5, 0xc7, 0xc1, 0x4b, 0x34, 0xa9, 0xa0, 0x09, 0x22, 0xa8, 0x17, 0xbc, 0x54, 0xda, 0x09, 0x45,
	0x76, 0xa1, 0xe6, 0xd1, 0x36, 0x0d, 0x46, 0xb4, 0x63, 0x0c, 0x00, 0x0d, 0x36, 0xe3, 0xb1, 0x53,
	0x0f, 0xf5, 0x52, 0x2b, 0xb1, 0x9c, 0x16, 0xb9, 0x1f, 0xab, 0x5e, 0x55, 0x48, 0x11, 0x9c, 0xdc,
	0x80, 0xa2, 0xe4, 0xb1, 0xea, 0xd5, 0x9d, 0xb5, 0x6d, 0x9c, 0x05, 0x46, 0x63, 0xaf, 0x1c, 0x8f,
	0x9d, 0xa2, 0x2c, 0xa9, 0x87, 0x7f, 0xdd, 0xdf, 0x0a, 0x50, 0x79, 0x11, 0x74, 0x28, 0x43, 0xcc,
	0x5c, 0x87, 0x65, 0xc5, 0x1c, 0x68, 0xd0, 0xa0, 0xdf, 0x23, 0x29, 0x92, 0xa8, 0x49, 0x28, 0xb2,
	0x03, 0xa5, 0xdd, 0x61, 0x74, 0xca, 0x42, 0x04, 0xcd, 0xf4, 0x31, 0x2a, 0xfd, 0xa8, 0xe1, 0xe9,
	0x5f, 0xb9, 0xf9, 0x51, 0xcf, 0x3f, 0x7b, 0x1e, 0xf6, 0x10, 0x3a, 0xa6, 0xad, 0x7a, 0xfe, 0x59,
	0x6b, 0x18, 0xf6, 0xbc, 0x84, 0x92, 0x75, 0xdf, 0x67, 0x23, 0x1a, 0x4a, 0xcd, 0x62, 0x8a, 0xc9,
	0xb6, 0x94, 0xa1, 0x6a, 0x4a, 0x22, 0xbc, 0xfc, 0x11, 0x93, 0x99, 0x57, 0xf0, 0x5a, 0xb2, 0xe0,
	0xa5, 0x17, 0x12, 0x78, 0x65, 0x78, 0x59, 0xdc, 0x7d, 0xd6, 0xef, 0xd3, 0x41, 0xa4, 0x2c, 0x4b,
	0x69, 0x71, 0xdb, 0x4a, 0xae, 0x0d, 0xb3, 0xac, 0x84, 0xd1, 0xa1, 0x30, 0x87, 0xda, 0x30, 0x92,
	0x68, 0xd4, 0x62, 0xcf, 0x66, 0xb0, 0xdb, 0x83, 0xa8, 0x47, 0x11, 0x3f, 0xa6, 0xdb, 0xa5, 0xc0,
	0x53, 0x3f, 0x6a, 0xcb, 0x2f, 0x06, 0x6d, 0xd6, 0x09, 0x06, 0x5d, 0x84, 0x4c, 0x39, 0xd9, 0x92,
	0x6a, 0xb1, 0x67, 0x33, 0xca, 0xf9, 0x5e, 0x8f, 0xb6, 0xb5, 0xf3, 0x60, 0x3b, 0x8f, 0xf2, 0xd4,
	0x79, 0x8b, 0x75, 0x7f, 0xcf, 0x43, 0x55, 0x47, 0x8d, 0x15, 0xbf, 0x09, 0x15, 0xc3, 0x9a, 0x41,
	0xb1, 0x16, 0x8f, 0x1d, 0x30, 0x21, 0x07, 0x1d, 0xcf, 0xa2, 0x13, 0x70, 0xe5, 0xe7, 0x01, 0x57,
	0x0a, 0xa7, 0x8e, 0x5d, 0xf1, 0x19, 0x70, 0xfa, 0x3f, 0x2c, 0xef, 0xb3, 0x41, 0x44, 0xf5, 0x78,
	0xd0, 0xc3, 0xaa, 0xad, 0x44, 0x9e, 0x21, 0xe4, 0x00, 0xd2, 0x0d, 0x7c, 0xe0, 0x47, 0x54, 0x97,
	0x1a, 0x07, 0x90, 0x69, 0xda, 0x8e, 0x1f, 0x51, 0x2f, 0xc3, 0xc9, 0xbd, 0x3d, 0xca, 0x7b, 0x01,
	0x15, 0xba, 0xc2, 0xb8, 0x77, 0xa8, 0x44, 0x9e, 0x21, 0x64, 0x22, 0x64, 0x07, 0xaa, 0x6c, 0xaa,
	0xa2, 0x62, 0x22, 0xb0, 0xcf, 0x54, 0x2a, 0x2d, 0x5a, 0x86, 0xf6, 0xc8, 0x17, 0xd2, 0x42, 0x0f,
	0x05, 0x0c, 0xed, 0xd4, 0x17, 0xd8, 0x98, 0x5e, 0x42, 0xb9, 0xbf, 0xe6, 0x61, 0x7d, 0x3f, 0xa4,
	0xbe, 0xc4, 0x27, 0xa6, 0x51, 0x8e, 0x73, 0x2b, 0x31, 0x6f, 0xee, 0xb3, 0xdb, 0x00, 0xbb, 0xed,
	0x28, 0x60, 0x83, 0x67, 0x67, 0x5c, 0x0d, 0x68, 0x8d, 0x35, 0x1f, 0xa5, 0xad, 0xe8, 0x8c, 0x53,
	0xcf, 0x66, 0xec, 0x54, 0x16, 0xde, 0x90, 0xca, 0x4c, 0xdd, 0x8b, 0x17, 0xd6, 0xdd, 0x5c, 0x26,
	0x07, 0x98, 0xf4, 0xf3, 0x2e, 0x93, 0x6b, 0x50, 0xf2, 0x18, 0x93, 0x3b, 0x96, 0x52, 0xad, 0x90,
	0x31, 0xdc, 0xce, 0x10, 0xb2, 0xbd, 0x8f, 0xfc, 0x50, 0x9d, 0xbc, 0x9c, 0xb6, 0x37, 0x47, 0x99,
	0xd4, 0x4c, 0x49, 0x77, 0x0f, 0xea, 0x13, 0xc9, 0x13, 0x7c, 0x41, 0xcc, 0xba, 0x3f, 0xe5, 0x60,
	0x4d, 0xeb, 0x3f, 0x0e, 0xc4, 0x62, 0xf9, 0xbf, 0xe8, 0x9e, 0xb6, 0x82, 0x39, 0xd0, 0xf9, 0x3e,
	0x37, 0x98, 0x24, 0x3d, 0x07, 0x36, 0xc8, 0x27, 0xd3, 0xe3, 0xfe, 0x9c, 0x83, 0x5a, 0xc6, 0x5d,
	0xc1, 0xc9, 0x67, 0x50, 0x94, 0x74, 0x23, 0x77, 0xb5, 0xb0, 0x55, 0xdd, 0xa9, 0xab, 0xb6, 0xb3,
	0xda, 0x58, 0x35, 0x41, 0x12, 0xb3, 0xbc, 0x0a, 0x32, 0x9c, 0x86, 0xeb, 0x13, 0xfa, 0xda, 0x60,
	0x3b, 0x81, 0xeb, 0x80, 0xbe, 0x8e, 0xbc, 0x84, 0x22, 0x0f, 0x60, 0x55, 0x6a, 0x1d, 0xf9, 0x5d,
	0xaa, 0x02, 0x57, 0x23, 0x6b, 0x23, 0x1e, 0x3b, 0x35, 0xa9, 0xd0, 0xe2, 0x7e, 0x97, 0xb6, 0x54,
	0x0a, 0x26, 0x05, 0xee, 0xf7, 0x39, 0x20, 0xb2, 0x25, 0x30, 0xb7, 0x0a, 0xb7, 0x73, 0x3f, 0x5e,
	0xec, 0x9a, 0xe4, 0x17, 0xe8, 0x89, 0xc2, 0xc5, 0x3d, 0xe1, 0x6e, 0xc2, 0xc6, 0x94, 0x5b, 0x82,
	0xbb, 0x1f, 0xc2, 0x3a, 0x8a, 0xe4, 0x9a, 0x41, 0xc6, 0x7c, 0x0f, 0xad, 0xa7, 0x50, 0x9f, 0xb0,
	0x14, 0x9c, 0x7c, 0xaa, 0x6f, 0x52, 0xab, 0x52, 0x35, 0x55, 0xa9, 0xe4, 0x82, 0x55, 0x38, 0xd5,
	0x91, 0xc8, 0x2a, 0x59, 0xb4, 0xfb, 0x43, 0x0e, 0xd6, 0xd4, 0x08, 0x4a, 0xe6, 0x84, 0x85, 0xf4,
	0x83, 0x39, 0xa6, 0xf3, 0xe2, 0xd3, 0x22, 0x0d, 0xb7, 0xf0, 0x86, 0x70, 0xeb, 0x50, 0xcb, 0x38,
	0x26, 0xb8, 0xfb, 0x81, 0x79, 0xd6, 0x2d, 0x96, 0xb8, 0x47, 0xb0, 0x66, 0x9b, 0x09, 0x4e, 0xee,
	0x26, 0xcf, 0x95, 0xc2, 0x8c, 0x1b, 0x25, 0x7d, 0x8c, 0x62, 0xba, 0x52, 0xd2, 0xbd, 0x07, 0x35,
	0xf3, 0xae, 0x5c, 0xcc, 0x85, 0x2f, 0x61, 0x3d, 0x6b, 0xf8, 0x16, 0x4e, 0x7c, 0x97, 0x83, 0x8a,
	0xda, 0x6c, 0x7e, 0x9c, 0xdf, 0x80, 0xf2, 0x33, 0xa6, 0xf5, 0xf2, 0x69, 0x49, 0x23, 0xd6, 0x32,
	0xaa, 0x16, 0xfd, 0x17, 0xc0, 0xbe, 0x02, 0x60, 0x5c, 0x12, 0xdc, 0xfd, 0x31, 0x07, 0x9b, 0xfa,
	0xa1, 0xf0, 0x6f, 0xeb, 0xca, 0x06, 0x5c, 0x9e, 0xe5, 0x99, 0xe0, 0xee, 0x03, 0xd8, 0x40, 0x91,
	0x5e, 0x5e, 0xac, 0xbe, 0x2f, 0xe0, 0xd2, 0xb4, 0xf1, 0xdb, 0xb7, 0xe7, 0xce, 0x2f, 0x25, 0xa8,
	0xee, 0xf9, 0x82, 0x3e, 0xa5, 0xe1, 0x28, 0x68, 0x53, 0xf2, 0x89, 0x7a, 0x77, 0x9b, 0x8f, 0x3f,
	0xb2, 0x99, 0xa2, 0xc6, 0xfa, 0xf2, 0x6c, 0x5e, 0x9e, 0x25, 0x16, 0x9c, 0xbc, 0x0f, 0x95, 0xe4,
	0xe3, 0x97, 0x90, 0x54, 0xc9, 0x7c, 0x73, 0x37, 0x37, 0xa6, 0x64, 0x82, 0x93, 0xf7, 0xac, 0x0f,
	0xbc, 0x7a, 0x16, 0xa6, 0xd2, 0x86, 0x4c, 0x8a, 0x04, 0x27, 0x9f, 0xc3, 0x6a, 0xe6, 0x0a, 0x25,
	0xda, 0xa3, 0xc9, 0x47, 0x49, 0xf3, 0x3f, 0x33, 0xe5, 0x82, 0x93, 0xfb, 0xc9, 0x93, 0x51, 0xe6,
	0x8e, 0x5c, 0xca, 0x5c, 0x3f, 0xba, 0x38, 0xcd, 0xcd, 0x19, 0x52, 0xc1, 0xc9, 0x43, 0x35, 0x3a,
	0xac, 0x0a, 0x93, 0x86, 0xd2, 0x9c, 0xbe, 0x28, 0x9a, 0x57, 0xce, 0x59, 0x51, 0x51, 0x64, 0x26,
	0xae, 0x89, 0x62, 0x72, 0x80, 0x9b, 0x28, 0xa6, 0xc7, 0xf3, 0x7d, 0xa8, 0x5a, 0x43, 0xcc, 0x44,
	0x91, 0x1d, 0xb8, 0x26, 0x8a, 0x89, 0x69, 0x47, 0xee, 0x99, 0x9e, 0xc2, 0xa3, 0x75, 0x65, 0x32,
	0xf3, 0xaf, 0x79, 0x69, 0x5a, 0x28, 0xb8, 0x04, 0x89, 0x3d, 0x6c, 0x0c, 0x48, 0x26, 0x26, 0x97,
	0x01, 0xc9, 0xd4, 0x5c, 0x7a, 0x17, 0x4a, 0x4a, 0x46, 0x6a, 0xb6, 0x86, 0x34, 0x59, 0xcf, 0x0a,
	0x04, 0x27, 0x5f, 0x01, 0x99, 0xee, 0x27, 0xf2, 0x5f, 0x53, 0x97, 0x19, 0x33, 0xa0, 0xf9, 0xbf,
	0xf3, 0x17, 0x05, 0x27, 0x87, 0xfa, 0x7e, 0xb4, 0x3a, 0x89, 0x5c, 0xb1, 0xd2, 0x9b, 0x6d, 0xcf,
	0x66, 0xf3, 0xbc, 0x25, 0xc1, 0xf7, 0x56, 0xbe, 0x81, 0xed, 0x5b, 0x0f, 0xe4, 0xfa, 0x2e, 0x0f,
	0x8e, 0x4b, 0xf8, 0x5f, 0xa6, 0x3b, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x3f, 0x09, 0x8f,
	0xa8, 0x12, 0x00, 0x00,
}
