// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base.proto

package baseApi

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserLoginReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,json=user_name,proto3" json:"user_name"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginReq) Reset()         { *m = UserLoginReq{} }
func (m *UserLoginReq) String() string { return proto.CompactTextString(m) }
func (*UserLoginReq) ProtoMessage()    {}
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}
func (m *UserLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginReq.Unmarshal(m, b)
}
func (m *UserLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginReq.Marshal(b, m, deterministic)
}
func (m *UserLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginReq.Merge(m, src)
}
func (m *UserLoginReq) XXX_Size() int {
	return xxx_messageInfo_UserLoginReq.Size(m)
}
func (m *UserLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginReq proto.InternalMessageInfo

func (m *UserLoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,json=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResp) Reset()         { *m = UserLoginResp{} }
func (m *UserLoginResp) String() string { return proto.CompactTextString(m) }
func (*UserLoginResp) ProtoMessage()    {}
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}
func (m *UserLoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResp.Unmarshal(m, b)
}
func (m *UserLoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResp.Marshal(b, m, deterministic)
}
func (m *UserLoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResp.Merge(m, src)
}
func (m *UserLoginResp) XXX_Size() int {
	return xxx_messageInfo_UserLoginResp.Size(m)
}
func (m *UserLoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResp proto.InternalMessageInfo

func (m *UserLoginResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserLoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserRegisterReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,json=user_name,proto3" json:"user_name"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterReq) Reset()         { *m = UserRegisterReq{} }
func (m *UserRegisterReq) String() string { return proto.CompactTextString(m) }
func (*UserRegisterReq) ProtoMessage()    {}
func (*UserRegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}
func (m *UserRegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterReq.Unmarshal(m, b)
}
func (m *UserRegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterReq.Marshal(b, m, deterministic)
}
func (m *UserRegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterReq.Merge(m, src)
}
func (m *UserRegisterReq) XXX_Size() int {
	return xxx_messageInfo_UserRegisterReq.Size(m)
}
func (m *UserRegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterReq proto.InternalMessageInfo

func (m *UserRegisterReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserRegisterResp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,json=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResp) Reset()         { *m = UserRegisterResp{} }
func (m *UserRegisterResp) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResp) ProtoMessage()    {}
func (*UserRegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{3}
}
func (m *UserRegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResp.Unmarshal(m, b)
}
func (m *UserRegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResp.Marshal(b, m, deterministic)
}
func (m *UserRegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResp.Merge(m, src)
}
func (m *UserRegisterResp) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResp.Size(m)
}
func (m *UserRegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResp proto.InternalMessageInfo

func (m *UserRegisterResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRegisterResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoReq) Reset()         { *m = UserInfoReq{} }
func (m *UserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoReq) ProtoMessage()    {}
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{4}
}
func (m *UserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReq.Unmarshal(m, b)
}
func (m *UserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReq.Marshal(b, m, deterministic)
}
func (m *UserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReq.Merge(m, src)
}
func (m *UserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoReq.Size(m)
}
func (m *UserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReq proto.InternalMessageInfo

func (m *UserInfoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserInfo struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,json=user_name,proto3" json:"user_name"`
	FollowCount          int64    `protobuf:"varint,3,opt,name=FollowCount,json=follow_count,proto3" json:"follow_count"`
	FollowerCount        int64    `protobuf:"varint,4,opt,name=FollowerCount,json=follower_count,proto3" json:"follower_count"`
	IsFollow             int64    `protobuf:"varint,5,opt,name=IsFollow,json=is_follow,proto3" json:"is_follow"`
	Avatar               string   `protobuf:"bytes,6,opt,name=Avatar,json=avatar,proto3" json:"avatar"`
	PublishNum           int64    `protobuf:"varint,7,opt,name=PublishNum,json=publish_num,proto3" json:"publish_num"`
	FavouriteNum         int64    `protobuf:"varint,8,opt,name=FavouriteNum,json=favourite_num,proto3" json:"favourite_num"`
	LikeNum              int64    `protobuf:"varint,9,opt,name=LikeNum,json=like_num,proto3" json:"like_num"`
	ReceivedLikeNum      int64    `protobuf:"varint,10,opt,name=ReceivedLikeNum,json=received_like_num,proto3" json:"received_like_num"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{5}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetFollowCount() int64 {
	if m != nil {
		return m.FollowCount
	}
	return 0
}

func (m *UserInfo) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *UserInfo) GetIsFollow() int64 {
	if m != nil {
		return m.IsFollow
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetPublishNum() int64 {
	if m != nil {
		return m.PublishNum
	}
	return 0
}

func (m *UserInfo) GetFavouriteNum() int64 {
	if m != nil {
		return m.FavouriteNum
	}
	return 0
}

func (m *UserInfo) GetLikeNum() int64 {
	if m != nil {
		return m.LikeNum
	}
	return 0
}

func (m *UserInfo) GetReceivedLikeNum() int64 {
	if m != nil {
		return m.ReceivedLikeNum
	}
	return 0
}

type UserInfoResp struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=User,json=user,proto3" json:"user"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoResp) Reset()         { *m = UserInfoResp{} }
func (m *UserInfoResp) String() string { return proto.CompactTextString(m) }
func (*UserInfoResp) ProtoMessage()    {}
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{6}
}
func (m *UserInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResp.Unmarshal(m, b)
}
func (m *UserInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResp.Marshal(b, m, deterministic)
}
func (m *UserInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResp.Merge(m, src)
}
func (m *UserInfoResp) XXX_Size() int {
	return xxx_messageInfo_UserInfoResp.Size(m)
}
func (m *UserInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResp proto.InternalMessageInfo

func (m *UserInfoResp) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type PublishListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishListReq) Reset()         { *m = PublishListReq{} }
func (m *PublishListReq) String() string { return proto.CompactTextString(m) }
func (*PublishListReq) ProtoMessage()    {}
func (*PublishListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{7}
}
func (m *PublishListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishListReq.Unmarshal(m, b)
}
func (m *PublishListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishListReq.Marshal(b, m, deterministic)
}
func (m *PublishListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishListReq.Merge(m, src)
}
func (m *PublishListReq) XXX_Size() int {
	return xxx_messageInfo_PublishListReq.Size(m)
}
func (m *PublishListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishListReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishListReq proto.InternalMessageInfo

func (m *PublishListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type VideoInfo struct {
	VideoId              string    `protobuf:"bytes,1,opt,name=VideoId,json=password,proto3" json:"video_id"`
	UserInfo             *UserInfo `protobuf:"bytes,2,opt,name=UserInfo,json=user_info,proto3" json:"user_info"`
	FavoriteCount        int64     `protobuf:"varint,3,opt,name=FavoriteCount,json=favourite_count,proto3" json:"favourite_count"`
	CommentCount         int64     `protobuf:"varint,4,opt,name=CommentCount,json=comment_count,proto3" json:"comment_count"`
	IsFavorite           int64     `protobuf:"varint,5,opt,name=IsFavorite,json=is_favourite,proto3" json:"is_favourite"`
	Title                string    `protobuf:"bytes,6,opt,name=Title,json=title,proto3" json:"title"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VideoInfo) Reset()         { *m = VideoInfo{} }
func (m *VideoInfo) String() string { return proto.CompactTextString(m) }
func (*VideoInfo) ProtoMessage()    {}
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{8}
}
func (m *VideoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoInfo.Unmarshal(m, b)
}
func (m *VideoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoInfo.Marshal(b, m, deterministic)
}
func (m *VideoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoInfo.Merge(m, src)
}
func (m *VideoInfo) XXX_Size() int {
	return xxx_messageInfo_VideoInfo.Size(m)
}
func (m *VideoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VideoInfo proto.InternalMessageInfo

func (m *VideoInfo) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *VideoInfo) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *VideoInfo) GetFavoriteCount() int64 {
	if m != nil {
		return m.FavoriteCount
	}
	return 0
}

func (m *VideoInfo) GetCommentCount() int64 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *VideoInfo) GetIsFavorite() int64 {
	if m != nil {
		return m.IsFavorite
	}
	return 0
}

func (m *VideoInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type PublishListResp struct {
	Video                *VideoInfo `protobuf:"bytes,1,opt,name=Video,json=video,proto3" json:"video"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PublishListResp) Reset()         { *m = PublishListResp{} }
func (m *PublishListResp) String() string { return proto.CompactTextString(m) }
func (*PublishListResp) ProtoMessage()    {}
func (*PublishListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{9}
}
func (m *PublishListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishListResp.Unmarshal(m, b)
}
func (m *PublishListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishListResp.Marshal(b, m, deterministic)
}
func (m *PublishListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishListResp.Merge(m, src)
}
func (m *PublishListResp) XXX_Size() int {
	return xxx_messageInfo_PublishListResp.Size(m)
}
func (m *PublishListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishListResp.DiscardUnknown(m)
}

var xxx_messageInfo_PublishListResp proto.InternalMessageInfo

func (m *PublishListResp) GetVideo() *VideoInfo {
	if m != nil {
		return m.Video
	}
	return nil
}

type CommentInfo struct {
	CommentId            string    `protobuf:"bytes,1,opt,name=CommentId,json=comment_id,proto3" json:"comment_id"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=User,json=user,proto3" json:"user"`
	VideoId              string    `protobuf:"bytes,3,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	Content              string    `protobuf:"bytes,4,opt,name=Content,json=content,proto3" json:"content"`
	PublishDate          int64     `protobuf:"varint,5,opt,name=PublishDate,json=publish_date,proto3" json:"publish_date"`
	Replies              int64     `protobuf:"varint,6,opt,name=Replies,json=replies,proto3" json:"replies"`
	LikeCount            int64     `protobuf:"varint,7,opt,name=LikeCount,json=like_count,proto3" json:"like_count"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommentInfo) Reset()         { *m = CommentInfo{} }
func (m *CommentInfo) String() string { return proto.CompactTextString(m) }
func (*CommentInfo) ProtoMessage()    {}
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{10}
}
func (m *CommentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentInfo.Unmarshal(m, b)
}
func (m *CommentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentInfo.Marshal(b, m, deterministic)
}
func (m *CommentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentInfo.Merge(m, src)
}
func (m *CommentInfo) XXX_Size() int {
	return xxx_messageInfo_CommentInfo.Size(m)
}
func (m *CommentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CommentInfo proto.InternalMessageInfo

func (m *CommentInfo) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *CommentInfo) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CommentInfo) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *CommentInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CommentInfo) GetPublishDate() int64 {
	if m != nil {
		return m.PublishDate
	}
	return 0
}

func (m *CommentInfo) GetReplies() int64 {
	if m != nil {
		return m.Replies
	}
	return 0
}

func (m *CommentInfo) GetLikeCount() int64 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

type CreateCommentReq struct {
	VideoId              string   `protobuf:"bytes,1,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	ActionType           int64    `protobuf:"varint,2,opt,name=ActionType,json=action_type,proto3" json:"action_type"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,json=content,proto3" json:"content"`
	CommentId            string   `protobuf:"bytes,4,opt,name=CommentId,json=comment_id,proto3" json:"comment_id"`
	UserID               string   `protobuf:"bytes,5,opt,name=UserID,json=user_id,proto3" json:"user_id"`
	RootId               string   `protobuf:"bytes,6,opt,name=RootId,json=root_id,proto3" json:"root_id"`
	ParentId             string   `protobuf:"bytes,7,opt,name=ParentId,json=parent_id,proto3" json:"parent_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentReq) Reset()         { *m = CreateCommentReq{} }
func (m *CreateCommentReq) String() string { return proto.CompactTextString(m) }
func (*CreateCommentReq) ProtoMessage()    {}
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{11}
}
func (m *CreateCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentReq.Unmarshal(m, b)
}
func (m *CreateCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentReq.Marshal(b, m, deterministic)
}
func (m *CreateCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentReq.Merge(m, src)
}
func (m *CreateCommentReq) XXX_Size() int {
	return xxx_messageInfo_CreateCommentReq.Size(m)
}
func (m *CreateCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentReq proto.InternalMessageInfo

func (m *CreateCommentReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *CreateCommentReq) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

func (m *CreateCommentReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateCommentReq) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *CreateCommentReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateCommentReq) GetRootId() string {
	if m != nil {
		return m.RootId
	}
	return ""
}

func (m *CreateCommentReq) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

type CreateCommentResp struct {
	CommentId            string   `protobuf:"bytes,1,opt,name=CommentId,json=comment_id,proto3" json:"comment_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentResp) Reset()         { *m = CreateCommentResp{} }
func (m *CreateCommentResp) String() string { return proto.CompactTextString(m) }
func (*CreateCommentResp) ProtoMessage()    {}
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{12}
}
func (m *CreateCommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentResp.Unmarshal(m, b)
}
func (m *CreateCommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentResp.Marshal(b, m, deterministic)
}
func (m *CreateCommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentResp.Merge(m, src)
}
func (m *CreateCommentResp) XXX_Size() int {
	return xxx_messageInfo_CreateCommentResp.Size(m)
}
func (m *CreateCommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentResp proto.InternalMessageInfo

func (m *CreateCommentResp) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

type CommentListReq struct {
	VideoId              string   `protobuf:"bytes,1,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,json=token,proto3" json:"token"`
	ParentID             string   `protobuf:"bytes,3,opt,name=ParentID,json=parent_id,proto3" json:"parent_id"`
	RootID               string   `protobuf:"bytes,4,opt,name=RootID,json=root_id,proto3" json:"root_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentListReq) Reset()         { *m = CommentListReq{} }
func (m *CommentListReq) String() string { return proto.CompactTextString(m) }
func (*CommentListReq) ProtoMessage()    {}
func (*CommentListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{13}
}
func (m *CommentListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentListReq.Unmarshal(m, b)
}
func (m *CommentListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentListReq.Marshal(b, m, deterministic)
}
func (m *CommentListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentListReq.Merge(m, src)
}
func (m *CommentListReq) XXX_Size() int {
	return xxx_messageInfo_CommentListReq.Size(m)
}
func (m *CommentListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentListReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommentListReq proto.InternalMessageInfo

func (m *CommentListReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *CommentListReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CommentListReq) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *CommentListReq) GetRootID() string {
	if m != nil {
		return m.RootID
	}
	return ""
}

type CommentListResp struct {
	List                 []*CommentInfo `protobuf:"bytes,1,rep,name=List,json=comment_info,proto3" json:"comment_info"`
	HasNext              int64          `protobuf:"varint,7,opt,name=HasNext,json=has_next,proto3" json:"has_next"`
	NextPageToken        string         `protobuf:"bytes,8,opt,name=NextPageToken,json=next_page_token,proto3" json:"next_page_token"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CommentListResp) Reset()         { *m = CommentListResp{} }
func (m *CommentListResp) String() string { return proto.CompactTextString(m) }
func (*CommentListResp) ProtoMessage()    {}
func (*CommentListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{14}
}
func (m *CommentListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentListResp.Unmarshal(m, b)
}
func (m *CommentListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentListResp.Marshal(b, m, deterministic)
}
func (m *CommentListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentListResp.Merge(m, src)
}
func (m *CommentListResp) XXX_Size() int {
	return xxx_messageInfo_CommentListResp.Size(m)
}
func (m *CommentListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentListResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommentListResp proto.InternalMessageInfo

func (m *CommentListResp) GetList() []*CommentInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *CommentListResp) GetHasNext() int64 {
	if m != nil {
		return m.HasNext
	}
	return 0
}

func (m *CommentListResp) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type LikeVideoActionReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	VideoId              string   `protobuf:"bytes,2,opt,name=VideoId,json=video_id,proto3" json:"video_id"`
	ActionType           int64    `protobuf:"varint,3,opt,name=ActionType,json=action_type,proto3" json:"action_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeVideoActionReq) Reset()         { *m = LikeVideoActionReq{} }
func (m *LikeVideoActionReq) String() string { return proto.CompactTextString(m) }
func (*LikeVideoActionReq) ProtoMessage()    {}
func (*LikeVideoActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{15}
}
func (m *LikeVideoActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeVideoActionReq.Unmarshal(m, b)
}
func (m *LikeVideoActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeVideoActionReq.Marshal(b, m, deterministic)
}
func (m *LikeVideoActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeVideoActionReq.Merge(m, src)
}
func (m *LikeVideoActionReq) XXX_Size() int {
	return xxx_messageInfo_LikeVideoActionReq.Size(m)
}
func (m *LikeVideoActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeVideoActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_LikeVideoActionReq proto.InternalMessageInfo

func (m *LikeVideoActionReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LikeVideoActionReq) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *LikeVideoActionReq) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type LikeVideoActionResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeVideoActionResp) Reset()         { *m = LikeVideoActionResp{} }
func (m *LikeVideoActionResp) String() string { return proto.CompactTextString(m) }
func (*LikeVideoActionResp) ProtoMessage()    {}
func (*LikeVideoActionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{16}
}
func (m *LikeVideoActionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeVideoActionResp.Unmarshal(m, b)
}
func (m *LikeVideoActionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeVideoActionResp.Marshal(b, m, deterministic)
}
func (m *LikeVideoActionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeVideoActionResp.Merge(m, src)
}
func (m *LikeVideoActionResp) XXX_Size() int {
	return xxx_messageInfo_LikeVideoActionResp.Size(m)
}
func (m *LikeVideoActionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeVideoActionResp.DiscardUnknown(m)
}

var xxx_messageInfo_LikeVideoActionResp proto.InternalMessageInfo

type VideoLikeListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,json=user_id,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoLikeListReq) Reset()         { *m = VideoLikeListReq{} }
func (m *VideoLikeListReq) String() string { return proto.CompactTextString(m) }
func (*VideoLikeListReq) ProtoMessage()    {}
func (*VideoLikeListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{17}
}
func (m *VideoLikeListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoLikeListReq.Unmarshal(m, b)
}
func (m *VideoLikeListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoLikeListReq.Marshal(b, m, deterministic)
}
func (m *VideoLikeListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoLikeListReq.Merge(m, src)
}
func (m *VideoLikeListReq) XXX_Size() int {
	return xxx_messageInfo_VideoLikeListReq.Size(m)
}
func (m *VideoLikeListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoLikeListReq.DiscardUnknown(m)
}

var xxx_messageInfo_VideoLikeListReq proto.InternalMessageInfo

func (m *VideoLikeListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type VideoLikeListResp struct {
	VideoList            []*VideoInfo `protobuf:"bytes,1,rep,name=VideoList,json=video_info,proto3" json:"video_info"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VideoLikeListResp) Reset()         { *m = VideoLikeListResp{} }
func (m *VideoLikeListResp) String() string { return proto.CompactTextString(m) }
func (*VideoLikeListResp) ProtoMessage()    {}
func (*VideoLikeListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{18}
}
func (m *VideoLikeListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoLikeListResp.Unmarshal(m, b)
}
func (m *VideoLikeListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoLikeListResp.Marshal(b, m, deterministic)
}
func (m *VideoLikeListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoLikeListResp.Merge(m, src)
}
func (m *VideoLikeListResp) XXX_Size() int {
	return xxx_messageInfo_VideoLikeListResp.Size(m)
}
func (m *VideoLikeListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoLikeListResp.DiscardUnknown(m)
}

var xxx_messageInfo_VideoLikeListResp proto.InternalMessageInfo

func (m *VideoLikeListResp) GetVideoList() []*VideoInfo {
	if m != nil {
		return m.VideoList
	}
	return nil
}

type LikeCommentReq struct {
	CommentID            string   `protobuf:"bytes,1,opt,name=CommentID,json=comment_id,proto3" json:"comment_id"`
	ActionType           int64    `protobuf:"varint,2,opt,name=ActionType,json=action_type,proto3" json:"action_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeCommentReq) Reset()         { *m = LikeCommentReq{} }
func (m *LikeCommentReq) String() string { return proto.CompactTextString(m) }
func (*LikeCommentReq) ProtoMessage()    {}
func (*LikeCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{19}
}
func (m *LikeCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeCommentReq.Unmarshal(m, b)
}
func (m *LikeCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeCommentReq.Marshal(b, m, deterministic)
}
func (m *LikeCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeCommentReq.Merge(m, src)
}
func (m *LikeCommentReq) XXX_Size() int {
	return xxx_messageInfo_LikeCommentReq.Size(m)
}
func (m *LikeCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_LikeCommentReq proto.InternalMessageInfo

func (m *LikeCommentReq) GetCommentID() string {
	if m != nil {
		return m.CommentID
	}
	return ""
}

func (m *LikeCommentReq) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type LikeCommentResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeCommentResp) Reset()         { *m = LikeCommentResp{} }
func (m *LikeCommentResp) String() string { return proto.CompactTextString(m) }
func (*LikeCommentResp) ProtoMessage()    {}
func (*LikeCommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{20}
}
func (m *LikeCommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeCommentResp.Unmarshal(m, b)
}
func (m *LikeCommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeCommentResp.Marshal(b, m, deterministic)
}
func (m *LikeCommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeCommentResp.Merge(m, src)
}
func (m *LikeCommentResp) XXX_Size() int {
	return xxx_messageInfo_LikeCommentResp.Size(m)
}
func (m *LikeCommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeCommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_LikeCommentResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UserLoginReq)(nil), "base.UserLoginReq")
	proto.RegisterType((*UserLoginResp)(nil), "base.UserLoginResp")
	proto.RegisterType((*UserRegisterReq)(nil), "base.UserRegisterReq")
	proto.RegisterType((*UserRegisterResp)(nil), "base.UserRegisterResp")
	proto.RegisterType((*UserInfoReq)(nil), "base.UserInfoReq")
	proto.RegisterType((*UserInfo)(nil), "base.UserInfo")
	proto.RegisterType((*UserInfoResp)(nil), "base.UserInfoResp")
	proto.RegisterType((*PublishListReq)(nil), "base.PublishListReq")
	proto.RegisterType((*VideoInfo)(nil), "base.VideoInfo")
	proto.RegisterType((*PublishListResp)(nil), "base.PublishListResp")
	proto.RegisterType((*CommentInfo)(nil), "base.CommentInfo")
	proto.RegisterType((*CreateCommentReq)(nil), "base.CreateCommentReq")
	proto.RegisterType((*CreateCommentResp)(nil), "base.CreateCommentResp")
	proto.RegisterType((*CommentListReq)(nil), "base.CommentListReq")
	proto.RegisterType((*CommentListResp)(nil), "base.CommentListResp")
	proto.RegisterType((*LikeVideoActionReq)(nil), "base.LikeVideoActionReq")
	proto.RegisterType((*LikeVideoActionResp)(nil), "base.LikeVideoActionResp")
	proto.RegisterType((*VideoLikeListReq)(nil), "base.VideoLikeListReq")
	proto.RegisterType((*VideoLikeListResp)(nil), "base.VideoLikeListResp")
	proto.RegisterType((*LikeCommentReq)(nil), "base.LikeCommentReq")
	proto.RegisterType((*LikeCommentResp)(nil), "base.LikeCommentResp")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 1195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5f, 0x4f, 0xe3, 0x46,
	0x10, 0x57, 0xfe, 0x90, 0x3f, 0x13, 0x92, 0x90, 0xa5, 0xb4, 0x69, 0x5e, 0x8c, 0xac, 0xab, 0x0e,
	0x55, 0x3d, 0xa0, 0x50, 0x9d, 0x5a, 0xae, 0xff, 0x08, 0x08, 0x15, 0x09, 0x21, 0xb4, 0x77, 0x3d,
	0xa9, 0x7d, 0x89, 0x4c, 0xb2, 0x04, 0x8b, 0x24, 0xf6, 0x79, 0x1d, 0xee, 0xee, 0x83, 0xf4, 0x5b,
	0xf4, 0xb5, 0x52, 0xd5, 0x3e, 0xf7, 0x6b, 0xf8, 0x03, 0xf8, 0xb1, 0x9f, 0xa0, 0xda, 0xd9, 0x5d,
	0x7b, 0xed, 0x40, 0x09, 0x52, 0xfb, 0x12, 0xcf, 0x8c, 0x67, 0x76, 0x77, 0x7e, 0xf3, 0x9b, 0xf1,
	0x06, 0xe0, 0xd2, 0xe1, 0x6c, 0xdb, 0x0f, 0xbc, 0xd0, 0x23, 0x65, 0x21, 0xf7, 0x9e, 0x8d, 0xdd,
	0xf0, 0x7a, 0x7e, 0xb9, 0x3d, 0xf4, 0xa6, 0x3b, 0x63, 0x6f, 0xec, 0xed, 0xe0, 0xcb, 0xcb, 0xf9,
	0x15, 0x6a, 0xa8, 0xa0, 0x24, 0x83, 0xec, 0x11, 0xac, 0xfe, 0xc8, 0x59, 0x70, 0xe6, 0x8d, 0xdd,
	0x19, 0x65, 0x6f, 0xc8, 0xa7, 0x50, 0x13, 0xfa, 0xb9, 0x33, 0x65, 0xdd, 0xc2, 0x66, 0x61, 0xab,
	0xde, 0x6f, 0xc6, 0x91, 0x55, 0x9f, 0x73, 0x16, 0x0c, 0x66, 0xce, 0x94, 0xd1, 0x54, 0x24, 0x5b,
	0x50, 0xbb, 0x70, 0x38, 0x7f, 0xeb, 0x05, 0xa3, 0x6e, 0x11, 0x7d, 0x57, 0xe3, 0xc8, 0xaa, 0xf9,
	0xca, 0x46, 0x13, 0xc9, 0x7e, 0x0d, 0x4d, 0x63, 0x17, 0xee, 0x93, 0x27, 0x50, 0x11, 0x86, 0xd3,
	0x91, 0xda, 0xa4, 0x11, 0x47, 0x56, 0x15, 0x57, 0x76, 0x47, 0x54, 0x0b, 0xc4, 0x82, 0x95, 0x57,
	0xde, 0x0d, 0x9b, 0xa9, 0xd5, 0xeb, 0x71, 0x64, 0xad, 0x84, 0xc2, 0x40, 0xe5, 0xc3, 0x1e, 0x43,
	0x5b, 0x2c, 0x43, 0xd9, 0xd8, 0xe5, 0xa1, 0x78, 0xfe, 0x5f, 0x09, 0xfc, 0x04, 0x6b, 0xd9, 0x8d,
	0xfe, 0xbb, 0x1c, 0xf6, 0xa1, 0x81, 0xcb, 0xcc, 0xae, 0x3c, 0x71, 0xfe, 0xa5, 0x56, 0xb5, 0xff,
	0x2e, 0xc9, 0x34, 0x45, 0xd4, 0x92, 0x07, 0x31, 0x81, 0x29, 0x3e, 0x00, 0xcc, 0x3e, 0x34, 0x4e,
	0xbc, 0xc9, 0xc4, 0x7b, 0x7b, 0xe4, 0xcd, 0x67, 0x61, 0xb7, 0xb4, 0x59, 0xd8, 0x2a, 0xf5, 0xd7,
	0xe2, 0xc8, 0x5a, 0xbd, 0x42, 0xf3, 0x60, 0x28, 0xec, 0x34, 0xa3, 0x91, 0xaf, 0xa0, 0x29, 0x83,
	0x58, 0x20, 0xc3, 0xca, 0x18, 0x46, 0xe2, 0xc8, 0x6a, 0x5d, 0xa9, 0x17, 0x2a, 0x30, 0xa7, 0x8b,
	0xb3, 0x9d, 0x72, 0x19, 0xdc, 0x5d, 0xc1, 0x28, 0x3c, 0x9b, 0xcb, 0x07, 0xd2, 0x91, 0xa6, 0x22,
	0xb1, 0xa1, 0x72, 0x78, 0xeb, 0x84, 0x4e, 0xd0, 0xad, 0x60, 0x16, 0x10, 0x47, 0x56, 0xc5, 0x41,
	0x0b, 0x55, 0x4f, 0xb2, 0x0b, 0x70, 0x31, 0xbf, 0x9c, 0xb8, 0xfc, 0xfa, 0x7c, 0x3e, 0xed, 0x56,
	0x71, 0xc5, 0x76, 0x1c, 0x59, 0x0d, 0x5f, 0x5a, 0x07, 0xb3, 0xf9, 0x94, 0x9a, 0x0a, 0x79, 0x0e,
	0xab, 0x27, 0xce, 0xad, 0x37, 0x0f, 0xdc, 0x90, 0x89, 0x98, 0x1a, 0xc6, 0x74, 0xe2, 0xc8, 0x6a,
	0x5e, 0x69, 0x3b, 0x46, 0x65, 0x55, 0xf2, 0x14, 0xaa, 0x67, 0xee, 0x0d, 0x86, 0xd4, 0x31, 0x04,
	0x19, 0x34, 0x71, 0x6f, 0xa4, 0x77, 0x22, 0x91, 0x43, 0x68, 0x53, 0x36, 0x64, 0xee, 0x2d, 0x1b,
	0xe9, 0x00, 0xc0, 0x80, 0x8d, 0x38, 0xb2, 0x3a, 0x81, 0x7a, 0x35, 0x48, 0x22, 0x17, 0x4d, 0xf6,
	0xd7, 0xb2, 0x57, 0x25, 0x53, 0xb8, 0x4f, 0x3e, 0x83, 0xb2, 0xd0, 0xb1, 0xea, 0x8d, 0xbd, 0xd6,
	0x36, 0xce, 0x02, 0xed, 0xd1, 0xaf, 0xc5, 0x91, 0x55, 0x16, 0x25, 0xa5, 0xf8, 0x6b, 0x3f, 0x87,
	0x96, 0xc2, 0xe4, 0xcc, 0xe5, 0xe1, 0xf2, 0x54, 0xfb, 0xa3, 0x08, 0xf5, 0xd7, 0xee, 0x88, 0x79,
	0xc8, 0xb5, 0xa7, 0x50, 0x95, 0x8a, 0x0e, 0xc2, 0x7c, 0x6f, 0x85, 0x49, 0x44, 0x25, 0x1d, 0x43,
	0x0e, 0x52, 0x82, 0x22, 0xdd, 0x16, 0x0f, 0x98, 0xd2, 0xcf, 0x15, 0x19, 0xa5, 0x22, 0x79, 0x01,
	0x4d, 0x51, 0x0c, 0x01, 0xb2, 0x49, 0xc0, 0xf5, 0x38, 0xb2, 0xda, 0x29, 0xfc, 0x92, 0x4a, 0x79,
	0x83, 0xa8, 0xe4, 0x91, 0x37, 0x9d, 0xb2, 0x59, 0x68, 0xb2, 0x10, 0x2b, 0x39, 0x94, 0x76, 0x15,
	0x99, 0x55, 0xc9, 0x1e, 0xc0, 0x29, 0xd7, 0xdb, 0x2a, 0x16, 0x22, 0xe5, 0x05, 0xf5, 0xf4, 0x1e,
	0x34, 0xa3, 0x61, 0x73, 0xbb, 0xe1, 0x84, 0x29, 0x2a, 0xca, 0xe6, 0x16, 0x06, 0x2a, 0x1f, 0xf6,
	0x11, 0xb4, 0x33, 0xa0, 0x73, 0x9f, 0xec, 0xc2, 0x0a, 0x22, 0xa8, 0xca, 0xd6, 0x96, 0xa8, 0x24,
	0x08, 0xcb, 0x45, 0x10, 0x50, 0x2a, 0x1f, 0xf6, 0x5f, 0x45, 0x68, 0xa8, 0x94, 0xb0, 0x06, 0xcf,
	0xa0, 0xae, 0x55, 0x5d, 0x85, 0x56, 0x1c, 0x59, 0xa0, 0xf3, 0x71, 0x47, 0xd4, 0x90, 0x13, 0x9a,
	0x14, 0x97, 0xa1, 0x89, 0x59, 0xe0, 0xd2, 0x5d, 0x05, 0xd6, 0x12, 0xf9, 0x04, 0xaa, 0x47, 0xde,
	0x2c, 0x64, 0x0a, 0x62, 0x45, 0x9f, 0xa1, 0x34, 0x51, 0x2d, 0x88, 0x51, 0xa2, 0x10, 0x38, 0x76,
	0xb2, 0xb8, 0xea, 0xf6, 0x1b, 0x39, 0x02, 0x57, 0x53, 0x13, 0x6b, 0x53, 0xe6, 0x4f, 0x5c, 0xc6,
	0x11, 0xd9, 0x92, 0x5c, 0x3b, 0x90, 0x26, 0xaa, 0x05, 0x01, 0x84, 0xe8, 0x25, 0x59, 0x67, 0xd9,
	0xe5, 0x08, 0x04, 0x76, 0x8c, 0x2c, 0xb2, 0x21, 0xdb, 0x7f, 0x16, 0x61, 0xed, 0x28, 0x60, 0x8e,
	0x60, 0x15, 0xa2, 0x23, 0x9a, 0xe0, 0x21, 0x42, 0x27, 0xf9, 0xee, 0x02, 0x1c, 0x0e, 0x43, 0xd7,
	0x9b, 0xbd, 0x7a, 0xef, 0xcb, 0x09, 0xaa, 0x66, 0x8a, 0x83, 0xd6, 0x41, 0xf8, 0xde, 0x67, 0xd4,
	0x54, 0x4c, 0x84, 0x4a, 0xff, 0x82, 0x50, 0xa6, 0x9c, 0xe5, 0x07, 0xcb, 0xa9, 0xbb, 0xf6, 0x18,
	0xb1, 0xbc, 0x6f, 0xda, 0x3f, 0x81, 0x0a, 0xf5, 0x3c, 0xb1, 0x62, 0x25, 0xf5, 0x0a, 0x3c, 0x0f,
	0x97, 0xd3, 0x82, 0x98, 0xbb, 0x17, 0x4e, 0x20, 0x77, 0xae, 0xa6, 0xdf, 0x04, 0x1f, 0x6d, 0xc2,
	0x33, 0x15, 0xed, 0x3e, 0x74, 0x72, 0xe0, 0x71, 0xff, 0x91, 0x54, 0xb4, 0x7f, 0x2d, 0x40, 0x4b,
	0xf9, 0xeb, 0x21, 0xb4, 0x34, 0xfe, 0x0f, 0x7d, 0x48, 0x8d, 0x64, 0x8e, 0x15, 0xde, 0xf7, 0x26,
	0x93, 0xc0, 0x73, 0x6c, 0x72, 0x37, 0x0f, 0x8f, 0xfd, 0x7b, 0x01, 0xda, 0x99, 0xe3, 0x72, 0x9f,
	0x7c, 0x07, 0x65, 0x21, 0x77, 0x0b, 0x9b, 0xa5, 0xad, 0xc6, 0x5e, 0x47, 0x76, 0x93, 0xd1, 0x9d,
	0x92, 0xdb, 0x49, 0xce, 0x62, 0xb2, 0x65, 0x34, 0x91, 0xf0, 0x0f, 0x0e, 0x3f, 0x67, 0xef, 0x34,
	0x65, 0x31, 0xe1, 0x6b, 0x87, 0x0f, 0x66, 0xec, 0x5d, 0x48, 0x13, 0x49, 0x4c, 0x41, 0xe1, 0x75,
	0xe1, 0x8c, 0x99, 0x4c, 0xbc, 0x86, 0x47, 0xc5, 0x29, 0x28, 0x1c, 0x06, 0xbe, 0x33, 0x66, 0x03,
	0x09, 0x41, 0xde, 0x60, 0xff, 0x52, 0x00, 0x22, 0x7a, 0x03, 0xb1, 0x95, 0xbc, 0x5d, 0x7a, 0xe4,
	0x9b, 0x35, 0x29, 0x3e, 0xa2, 0x27, 0x4a, 0x0f, 0xf7, 0x84, 0xbd, 0x01, 0xeb, 0x0b, 0xc7, 0xe2,
	0xbe, 0xfd, 0x25, 0xac, 0xa1, 0x49, 0xbc, 0x7b, 0xdc, 0xe7, 0xe9, 0x25, 0x74, 0x72, 0x91, 0xdc,
	0x27, 0xdf, 0xaa, 0x4f, 0x96, 0x51, 0xa9, 0x85, 0x39, 0x8b, 0x3c, 0x55, 0x99, 0x88, 0x2a, 0x19,
	0xb2, 0xfd, 0x06, 0x5a, 0x72, 0xb0, 0x24, 0x63, 0xc2, 0x20, 0xfa, 0xf1, 0x12, 0x33, 0xf7, 0xd1,
	0xc3, 0xc2, 0xee, 0x40, 0x3b, 0xb3, 0x25, 0xf7, 0xf7, 0x7e, 0x2b, 0x43, 0xa3, 0xef, 0x70, 0xf6,
	0x92, 0x05, 0xb7, 0xee, 0x90, 0x91, 0x6f, 0xe4, 0xf7, 0x5f, 0x5f, 0x42, 0xc9, 0x46, 0x3a, 0xca,
	0x8d, 0x1b, 0x70, 0xef, 0xc3, 0xbb, 0xcc, 0xdc, 0x27, 0x5f, 0x40, 0x3d, 0xb9, 0x84, 0x13, 0x92,
	0x3a, 0xe9, 0xbb, 0x7f, 0x6f, 0x7d, 0xc1, 0xc6, 0x7d, 0xf2, 0xb9, 0x71, 0xd1, 0xec, 0x64, 0xbf,
	0x1d, 0x22, 0x86, 0xe4, 0x4d, 0xdc, 0x27, 0x07, 0xc9, 0xc8, 0x17, 0xf8, 0x93, 0x0f, 0xa4, 0x4b,
	0xf6, 0xf2, 0xd1, 0xdb, 0xb8, 0xc3, 0xca, 0x7d, 0xf2, 0x3d, 0x34, 0x33, 0x53, 0x86, 0xa8, 0x6c,
	0xf2, 0x73, 0xbb, 0xf7, 0xd1, 0x9d, 0x76, 0xb9, 0xbb, 0xd1, 0xb3, 0x7a, 0xf7, 0xec, 0xd4, 0xd1,
	0xbb, 0xe7, 0x9b, 0xfb, 0x44, 0x16, 0xc1, 0x60, 0x27, 0xe9, 0x4a, 0xcf, 0xc5, 0x5e, 0xea, 0x7d,
	0x7c, 0xcf, 0x1b, 0x99, 0x45, 0x86, 0x94, 0x3a, 0x8b, 0x3c, 0xc7, 0x75, 0x16, 0x8b, 0x0c, 0x3e,
	0x80, 0x86, 0x41, 0x07, 0x9d, 0x45, 0x96, 0x94, 0x3a, 0x8b, 0x1c, 0x6f, 0xfa, 0xab, 0x3f, 0xc3,
	0xf6, 0xce, 0x0b, 0xf1, 0xea, 0xd0, 0x77, 0x2f, 0x2b, 0xf8, 0x47, 0x6f, 0xff, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa2, 0xf8, 0x34, 0xd3, 0x2b, 0x0e, 0x00, 0x00,
}
