name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  GO_VERSION: '1.21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        # CGO_ENABLED=0 is required to run on SCF
        # https://github.com/aws-amplify/amplify-cli/issues/12577
        run: |
          go mod tidy
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o snaptime-server .
      - name: Copy artifact
        run: |
          mkdir action-product
          cp snaptime-server ./action-product/
          cp -r ./serverless/* ./action-product/
      - name: Show files to upload
        run: |
          cd action-product
          chmod +x snaptime-server
          chmod +x scf_bootstrap
          ls -lah
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snaptime-server
          path: action-product

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: snaptime-server
          path: ./serverless
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Replace secrets and variables
        run: |
          sed -i "s|__PLACEHOLDER_DB_PASSWORD__|${{ secrets.DB_PASSWORD }}|g" ./serverless/serverless.yaml
          sed -i "s|__PLACEHOLDER_REDIS_PASSWORD__|${{ secrets.REDIS_PASSWORD }}|g" ./serverless/serverless.yaml
          sed -i "s|__PLACEHOLDER_QINIU_ACCESS_KEY__|${{ secrets.QINIU_ACCESS_KEY }}|g" ./serverless/serverless.yaml
          sed -i "s|__PLACEHOLDER_QINIU_SECRET_KEY__|${{ secrets.QINIU_SECRET_KEY }}|g" ./serverless/serverless.yaml
      - name: Install Serverless Cloud Framework
        run: npm install -g serverless-cloud-framework
      - name: Configure SCF credentials
        run: |
          scf credentials set --secretId ${{ vars.TENCENT_SCF_SECRET_ID }} \
                              --secretKey ${{ secrets.TENCENT_SCF_SECRET_KEY }}
      - name: Show files to deploy
        run: |
          cd serverless
          chmod +x snaptime-server
          chmod +x scf_bootstrap
          ls -lah
      - name: Deploy
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then export STAGE=prod; else export STAGE=dev; fi
          cd serverless
          scf deploy --force --stage $STAGE
